/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_PROPS_ARGS_H
#define EDGER8R_PROPS_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _enc_props_args_t
{
    oe_result_t _result;
    int _retval;
    int* ret;
} enc_props_args_t;

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** Trusted function IDs ****/
enum
{
    props_fcn_id_enc_props = 0,
    props_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{

    props_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_PROPS_ARGS_H
