/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SAMPLEAPP_ARGS_H
#define EDGER8R_SAMPLEAPP_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _secure_str_patching_args_t
{
    oe_result_t _result;
    int _retval;
    char* src;
    size_t src_len;
    char* dst;
    size_t dst_length;
} secure_str_patching_args_t;

/**** OCALL marshalling structs. ****/
typedef struct _unsecure_str_patching_args_t
{
    oe_result_t _result;
    int _retval;
    char* src;
    size_t src_len;
    char* dst;
    size_t dst_length;
} unsecure_str_patching_args_t;

/**** Trusted function IDs ****/
enum
{
    SampleApp_fcn_id_secure_str_patching = 0,
    SampleApp_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{
    SampleApp_fcn_id_unsecure_str_patching = 0,
    SampleApp_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_SAMPLEAPP_ARGS_H
