/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_GETENCLAVE_ARGS_H
#define EDGER8R_GETENCLAVE_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _test_get_enclave_ecall_args_t
{
    oe_result_t _result;
    oe_result_t _retval;
    oe_enclave_t* enclaveParam;
} test_get_enclave_ecall_args_t;

/**** OCALL marshalling structs. ****/
typedef struct _test_get_enclave_ocall_args_t
{
    oe_result_t _result;
    oe_enclave_t* enclaveParam;
} test_get_enclave_ocall_args_t;

/**** Trusted function IDs ****/
enum
{
    getenclave_fcn_id_test_get_enclave_ecall = 0,
    getenclave_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{
    getenclave_fcn_id_test_get_enclave_ocall = 0,
    getenclave_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_GETENCLAVE_ARGS_H
