/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_MBED_U_H
#define EDGER8R_MBED_U_H

#include <openenclave/host.h>

#include "mbed_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_mbed_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
#ifdef OE_CONTEXT_SWITCHLESS_EXPERIMENTAL_FEATURE
    const oe_enclave_config_t* configs,
    uint32_t config_count,
#else
    const void* config,
    uint32_t config_size,
#endif
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t test(
    oe_enclave_t* enclave,
    int* _retval,
    const char* in_testname,
    char* out_testname,
    mbed_args* args);

/**** OCALL prototypes. ****/
int mbed_test_open(
    const char* path,
    int flags,
    mode_t mode);

ssize_t mbed_test_read(
    int fd,
    char* buf,
    size_t buf_len);

int mbed_test_close(int fd);

void ocall_exit(int arg);

OE_EXTERNC_END

#endif // EDGER8R_MBED_U_H
