/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "sgx_u.h"

#include <openenclave/edger8r/host.h>

#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN

/**** ECALL function wrappers. ****/

oe_result_t oe_get_sgx_report_ecall(
    oe_enclave_t* enclave,
    oe_result_t* _retval,
    const void* opt_params,
    size_t opt_params_size,
    sgx_report_t* report)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshalling struct. */
    oe_get_sgx_report_ecall_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Deep copy buffer. */
    /* No pointers to save for deep copy. */

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.opt_params = (void*)opt_params;
    _args.opt_params_size = opt_params_size;
    _args.report = (sgx_report_t*)report;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(oe_get_sgx_report_ecall_args_t));
    if (opt_params)
        OE_ADD_SIZE(_input_buffer_size, _args.opt_params_size);
    
    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(oe_get_sgx_report_ecall_args_t));
    if (report)
        OE_ADD_SIZE(_output_buffer_size, sizeof(sgx_report_t));
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (oe_get_sgx_report_ecall_args_t*)_input_buffer;
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    if (opt_params)
        OE_WRITE_IN_PARAM(opt_params, _args.opt_params_size, void*);
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function. */
    if ((_result = oe_call_enclave_function(
             enclave,
             sgx_fcn_id_oe_get_sgx_report_ecall,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size,
             &_output_bytes_written)) != OE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (oe_get_sgx_report_ecall_args_t*)_output_buffer;
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Check if the call succeeded. */
    if ((_result = _pargs_out->_result) != OE_OK)
        goto done;
    
    /* Currently exactly _output_buffer_size bytes must be written. */
    if (_output_bytes_written != _output_buffer_size)
    {
        _result = OE_FAILURE;
        goto done;
    }
    
    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->_retval;
    /* No pointers to restore for deep copy. */
    OE_READ_OUT_PARAM(report, (size_t)(sizeof(sgx_report_t)));

    _result = OE_OK;

done:
    if (_buffer)
        free(_buffer);

    /* No `_ptrs` to free for deep copy. */

    return _result;
}

/**** OCALL functions. ****/

void ocall_oe_get_qetarget_info_ocall(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters. */
    oe_get_qetarget_info_ocall_args_t* pargs_in = (oe_get_qetarget_info_ocall_args_t*)input_buffer;
    oe_get_qetarget_info_ocall_args_t* pargs_out = (oe_get_qetarget_info_ocall_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid. */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;
    }

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->target_info)
        OE_SET_OUT_POINTER(target_info, sizeof(sgx_target_info_t), sgx_target_info_t*);

    /* Call user function. */
    pargs_out->_retval = oe_get_qetarget_info_ocall(
        pargs_in->target_info);

    /* Propagate errno back to enclave. */
    /* Errno propagation not enabled. */

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ocall_oe_get_quote_ocall(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters. */
    oe_get_quote_ocall_args_t* pargs_in = (oe_get_quote_ocall_args_t*)input_buffer;
    oe_get_quote_ocall_args_t* pargs_out = (oe_get_quote_ocall_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid. */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;
    }

    /* Set in and in-out pointers. */
    if (pargs_in->sgx_report)
        OE_SET_IN_POINTER(sgx_report, sizeof(sgx_report_t), sgx_report_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->quote)
        OE_SET_OUT_POINTER(quote, pargs_in->quote_size, void*);
    if (pargs_in->quote_size_out)
        OE_SET_OUT_POINTER(quote_size_out, sizeof(size_t), size_t*);

    /* Call user function. */
    pargs_out->_retval = oe_get_quote_ocall(
        (const sgx_report_t*)pargs_in->sgx_report,
        pargs_in->quote,
        pargs_in->quote_size,
        pargs_in->quote_size_out);

    /* Propagate errno back to enclave. */
    /* Errno propagation not enabled. */

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ocall_oe_get_qe_identify_info_ocall(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters. */
    oe_get_qe_identify_info_ocall_args_t* pargs_in = (oe_get_qe_identify_info_ocall_args_t*)input_buffer;
    oe_get_qe_identify_info_ocall_args_t* pargs_out = (oe_get_qe_identify_info_ocall_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid. */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;
    }

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->qe_id_info)
        OE_SET_OUT_POINTER(qe_id_info, pargs_in->qe_id_info_size, void*);
    if (pargs_in->qe_id_info_size_out)
        OE_SET_OUT_POINTER(qe_id_info_size_out, sizeof(size_t), size_t*);
    if (pargs_in->issuer_chain)
        OE_SET_OUT_POINTER(issuer_chain, pargs_in->issuer_chain_size, void*);
    if (pargs_in->issuer_chain_size_out)
        OE_SET_OUT_POINTER(issuer_chain_size_out, sizeof(size_t), size_t*);

    /* Call user function. */
    pargs_out->_retval = oe_get_qe_identify_info_ocall(
        pargs_in->qe_id_info,
        pargs_in->qe_id_info_size,
        pargs_in->qe_id_info_size_out,
        pargs_in->issuer_chain,
        pargs_in->issuer_chain_size,
        pargs_in->issuer_chain_size_out);

    /* Propagate errno back to enclave. */
    /* Errno propagation not enabled. */

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ocall_oe_get_revocation_info_ocall(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters. */
    oe_get_revocation_info_ocall_args_t* pargs_in = (oe_get_revocation_info_ocall_args_t*)input_buffer;
    oe_get_revocation_info_ocall_args_t* pargs_out = (oe_get_revocation_info_ocall_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid. */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;
    }

    /* Set in and in-out pointers. */
    if (pargs_in->fmspc)
        OE_SET_IN_POINTER(fmspc, sizeof(uint8_t[6]), uint8_t*);
    if (pargs_in->crl_urls0)
        OE_SET_IN_POINTER(crl_urls0, pargs_in->crl_urls0_len * sizeof(char), char*);
    if (pargs_in->crl_urls1)
        OE_SET_IN_POINTER(crl_urls1, pargs_in->crl_urls1_len * sizeof(char), char*);
    if (pargs_in->crl_urls2)
        OE_SET_IN_POINTER(crl_urls2, pargs_in->crl_urls2_len * sizeof(char), char*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->tcb_info)
        OE_SET_OUT_POINTER(tcb_info, pargs_in->tcb_info_size, void*);
    if (pargs_in->tcb_info_size_out)
        OE_SET_OUT_POINTER(tcb_info_size_out, sizeof(size_t), size_t*);
    if (pargs_in->tcb_issuer_chain)
        OE_SET_OUT_POINTER(tcb_issuer_chain, pargs_in->tcb_issuer_chain_size, void*);
    if (pargs_in->tcb_issuer_chain_size_out)
        OE_SET_OUT_POINTER(tcb_issuer_chain_size_out, sizeof(size_t), size_t*);
    if (pargs_in->crl0)
        OE_SET_OUT_POINTER(crl0, pargs_in->crl0_size, void*);
    if (pargs_in->crl0_size_out)
        OE_SET_OUT_POINTER(crl0_size_out, sizeof(size_t), size_t*);
    if (pargs_in->crl1)
        OE_SET_OUT_POINTER(crl1, pargs_in->crl1_size, void*);
    if (pargs_in->crl1_size_out)
        OE_SET_OUT_POINTER(crl1_size_out, sizeof(size_t), size_t*);
    if (pargs_in->crl2)
        OE_SET_OUT_POINTER(crl2, pargs_in->crl2_size, void*);
    if (pargs_in->crl2_size_out)
        OE_SET_OUT_POINTER(crl2_size_out, sizeof(size_t), size_t*);
    if (pargs_in->crl_issuer_chain0)
        OE_SET_OUT_POINTER(crl_issuer_chain0, pargs_in->crl_issuer_chain0_size, void*);
    if (pargs_in->crl_issuer_chain0_size_out)
        OE_SET_OUT_POINTER(crl_issuer_chain0_size_out, sizeof(size_t), size_t*);
    if (pargs_in->crl_issuer_chain1)
        OE_SET_OUT_POINTER(crl_issuer_chain1, pargs_in->crl_issuer_chain1_size, void*);
    if (pargs_in->crl_issuer_chain1_size_out)
        OE_SET_OUT_POINTER(crl_issuer_chain1_size_out, sizeof(size_t), size_t*);
    if (pargs_in->crl_issuer_chain2)
        OE_SET_OUT_POINTER(crl_issuer_chain2, pargs_in->crl_issuer_chain2_size, void*);
    if (pargs_in->crl_issuer_chain2_size_out)
        OE_SET_OUT_POINTER(crl_issuer_chain2_size_out, sizeof(size_t), size_t*);

    /* Call user function. */
    pargs_out->_retval = oe_get_revocation_info_ocall(
        *(uint8_t(*)[6])pargs_in->fmspc,
        pargs_in->num_crl_urls,
        (const char*)pargs_in->crl_urls0,
        (const char*)pargs_in->crl_urls1,
        (const char*)pargs_in->crl_urls2,
        pargs_in->tcb_info,
        pargs_in->tcb_info_size,
        pargs_in->tcb_info_size_out,
        pargs_in->tcb_issuer_chain,
        pargs_in->tcb_issuer_chain_size,
        pargs_in->tcb_issuer_chain_size_out,
        pargs_in->crl0,
        pargs_in->crl0_size,
        pargs_in->crl0_size_out,
        pargs_in->crl1,
        pargs_in->crl1_size,
        pargs_in->crl1_size_out,
        pargs_in->crl2,
        pargs_in->crl2_size,
        pargs_in->crl2_size_out,
        pargs_in->crl_issuer_chain0,
        pargs_in->crl_issuer_chain0_size,
        pargs_in->crl_issuer_chain0_size_out,
        pargs_in->crl_issuer_chain1,
        pargs_in->crl_issuer_chain1_size,
        pargs_in->crl_issuer_chain1_size_out,
        pargs_in->crl_issuer_chain2,
        pargs_in->crl_issuer_chain2_size,
        pargs_in->crl_issuer_chain2_size_out);

    /* Propagate errno back to enclave. */
    /* Errno propagation not enabled. */

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ocall_oe_backtrace_symbols_ocall(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters. */
    oe_backtrace_symbols_ocall_args_t* pargs_in = (oe_backtrace_symbols_ocall_args_t*)input_buffer;
    oe_backtrace_symbols_ocall_args_t* pargs_out = (oe_backtrace_symbols_ocall_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid. */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;
    }

    /* Set in and in-out pointers. */
    if (pargs_in->buffer)
        OE_SET_IN_POINTER(buffer, (pargs_in->size * sizeof(uint64_t)), uint64_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->symbols_buffer)
        OE_SET_OUT_POINTER(symbols_buffer, pargs_in->symbols_buffer_size, void*);
    if (pargs_in->symbols_buffer_size_out)
        OE_SET_OUT_POINTER(symbols_buffer_size_out, sizeof(size_t), size_t*);

    /* Call user function. */
    pargs_out->_retval = oe_backtrace_symbols_ocall(
        pargs_in->oe_enclave,
        (const uint64_t*)pargs_in->buffer,
        pargs_in->size,
        pargs_in->symbols_buffer,
        pargs_in->symbols_buffer_size,
        pargs_in->symbols_buffer_size_out);

    /* Propagate errno back to enclave. */
    /* Errno propagation not enabled. */

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ocall_oe_thread_wake_wait_ocall(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters. */
    oe_thread_wake_wait_ocall_args_t* pargs_in = (oe_thread_wake_wait_ocall_args_t*)input_buffer;
    oe_thread_wake_wait_ocall_args_t* pargs_out = (oe_thread_wake_wait_ocall_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid. */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;
    }

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    /* There were no out nor in-out parameters. */

    /* Call user function. */
    oe_thread_wake_wait_ocall(
        pargs_in->oe_enclave,
        pargs_in->waiter_tcs,
        pargs_in->self_tcs);

    /* Propagate errno back to enclave. */
    /* Errno propagation not enabled. */

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ocall_oe_get_cpuid_table_ocall(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters. */
    oe_get_cpuid_table_ocall_args_t* pargs_in = (oe_get_cpuid_table_ocall_args_t*)input_buffer;
    oe_get_cpuid_table_ocall_args_t* pargs_out = (oe_get_cpuid_table_ocall_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid. */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;
    }

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->cpuid_table_buffer)
        OE_SET_OUT_POINTER(cpuid_table_buffer, pargs_in->cpuid_table_buffer_size, void*);

    /* Call user function. */
    pargs_out->_retval = oe_get_cpuid_table_ocall(
        pargs_in->cpuid_table_buffer,
        pargs_in->cpuid_table_buffer_size);

    /* Propagate errno back to enclave. */
    /* Errno propagation not enabled. */

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

/**** OCALL function table. ****/

static oe_ocall_func_t __sgx_ocall_function_table[] = {
    (oe_ocall_func_t) ocall_oe_get_qetarget_info_ocall,
    (oe_ocall_func_t) ocall_oe_get_quote_ocall,
    (oe_ocall_func_t) ocall_oe_get_qe_identify_info_ocall,
    (oe_ocall_func_t) ocall_oe_get_revocation_info_ocall,
    (oe_ocall_func_t) ocall_oe_backtrace_symbols_ocall,
    (oe_ocall_func_t) ocall_oe_thread_wake_wait_ocall,
    (oe_ocall_func_t) ocall_oe_get_cpuid_table_ocall,
    NULL
};

oe_result_t oe_create_sgx_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
#ifdef OE_CONTEXT_SWITCHLESS_EXPERIMENTAL_FEATURE
    const oe_enclave_config_t* configs,
    uint32_t config_count,
#else
    const void* config,
    uint32_t config_size,
#endif
    oe_enclave_t** enclave)
{
    return oe_create_enclave(
               path,
               type,
               flags,
#ifdef OE_CONTEXT_SWITCHLESS_EXPERIMENTAL_FEATURE
               configs,
               config_count,
#else
               config,
               config_size,
#endif
               __sgx_ocall_function_table,
               7,
               enclave);
}

OE_EXTERNC_END
