/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ALL_U_H
#define EDGER8R_ALL_U_H

#include <openenclave/host.h>

#include "all_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_all_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
#ifdef OE_CONTEXT_SWITCHLESS_EXPERIMENTAL_FEATURE
    const oe_enclave_config_t* configs,
    uint32_t config_count,
#else
    const void* config,
    uint32_t config_size,
#endif
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t configure(
    oe_enclave_t* enclave,
    uint8_t enabled[4]);

oe_result_t aliasing_a(
    oe_enclave_t* enclave,
    int* _retval,
    const char* d,
    size_t c);

oe_result_t aliasing_b(
    oe_enclave_t* enclave,
    int* _retval,
    char** e,
    size_t* g,
    size_t f,
    char* h,
    size_t i,
    size_t* j);

oe_result_t aliasing_c(
    oe_enclave_t* enclave,
    int* _retval,
    char a[2]);

oe_result_t ecall_array_char(
    oe_enclave_t* enclave,
    char a1[2],
    char a2[2][2],
    char a3[3][3],
    char a4[4][4]);

oe_result_t ecall_array_wchar_t(
    oe_enclave_t* enclave,
    wchar_t a1[2],
    wchar_t a2[2][2],
    wchar_t a3[3][3],
    wchar_t a4[4][4]);

oe_result_t ecall_array_short(
    oe_enclave_t* enclave,
    short int a1[2],
    short int a2[2][2],
    short int a3[3][3],
    short int a4[4][4]);

oe_result_t ecall_array_int(
    oe_enclave_t* enclave,
    int a1[2],
    int a2[2][2],
    int a3[3][3],
    int a4[4][4]);

oe_result_t ecall_array_float(
    oe_enclave_t* enclave,
    float a1[2],
    float a2[2][2],
    float a3[3][3],
    float a4[4][4]);

oe_result_t ecall_array_double(
    oe_enclave_t* enclave,
    double a1[2],
    double a2[2][2],
    double a3[3][3],
    double a4[4][4]);

oe_result_t ecall_array_long(
    oe_enclave_t* enclave,
    long int a1[2],
    long int a2[2][2],
    long int a3[3][3],
    long int a4[4][4]);

oe_result_t ecall_array_size_t(
    oe_enclave_t* enclave,
    size_t a1[2],
    size_t a2[2][2],
    size_t a3[3][3],
    size_t a4[4][4]);

oe_result_t ecall_array_unsigned(
    oe_enclave_t* enclave,
    unsigned int a1[2],
    unsigned int a2[2][2],
    unsigned int a3[3][3],
    unsigned int a4[4][4]);

oe_result_t ecall_array_int8_t(
    oe_enclave_t* enclave,
    int8_t a1[2],
    int8_t a2[2][2],
    int8_t a3[3][3],
    int8_t a4[4][4]);

oe_result_t ecall_array_int16_t(
    oe_enclave_t* enclave,
    int16_t a1[2],
    int16_t a2[2][2],
    int16_t a3[3][3],
    int16_t a4[4][4]);

oe_result_t ecall_array_int32_t(
    oe_enclave_t* enclave,
    int32_t a1[2],
    int32_t a2[2][2],
    int32_t a3[3][3],
    int32_t a4[4][4]);

oe_result_t ecall_array_int64_t(
    oe_enclave_t* enclave,
    int64_t a1[2],
    int64_t a2[2][2],
    int64_t a3[3][3],
    int64_t a4[4][4]);

oe_result_t ecall_array_uint8_t(
    oe_enclave_t* enclave,
    uint8_t a1[2],
    uint8_t a2[2][2],
    uint8_t a3[3][3],
    uint8_t a4[4][4]);

oe_result_t ecall_array_uint16_t(
    oe_enclave_t* enclave,
    uint16_t a1[2],
    uint16_t a2[2][2],
    uint16_t a3[3][3],
    uint16_t a4[4][4]);

oe_result_t ecall_array_uint32_t(
    oe_enclave_t* enclave,
    uint32_t a1[2],
    uint32_t a2[2][2],
    uint32_t a3[3][3],
    uint32_t a4[4][4]);

oe_result_t ecall_array_uint64_t(
    oe_enclave_t* enclave,
    uint64_t a1[2],
    uint64_t a2[2][2],
    uint64_t a3[3][3],
    uint64_t a4[4][4]);

oe_result_t ecall_array_long_long(
    oe_enclave_t* enclave,
    long long a1[2],
    long long a2[2][2],
    long long a3[3][3],
    long long a4[4][4]);

oe_result_t ecall_array_long_double(
    oe_enclave_t* enclave,
    long double a1[2],
    long double a2[2][2],
    long double a3[3][3],
    long double a4[4][4]);

oe_result_t ecall_array_unsigned_char(
    oe_enclave_t* enclave,
    unsigned char a1[2],
    unsigned char a2[2][2],
    unsigned char a3[3][3],
    unsigned char a4[4][4]);

oe_result_t ecall_array_unsigned_short(
    oe_enclave_t* enclave,
    unsigned short int a1[2],
    unsigned short int a2[2][2],
    unsigned short int a3[3][3],
    unsigned short int a4[4][4]);

oe_result_t ecall_array_unsigned_int(
    oe_enclave_t* enclave,
    unsigned int a1[2],
    unsigned int a2[2][2],
    unsigned int a3[3][3],
    unsigned int a4[4][4]);

oe_result_t ecall_array_unsigned_long(
    oe_enclave_t* enclave,
    unsigned long int a1[2],
    unsigned long int a2[2][2],
    unsigned long int a3[3][3],
    unsigned long int a4[4][4]);

oe_result_t ecall_array_unsigned_long_long(
    oe_enclave_t* enclave,
    unsigned long long a1[2],
    unsigned long long a2[2][2],
    unsigned long long a3[3][3],
    unsigned long long a4[4][4]);

oe_result_t test_array_edl_ocalls(oe_enclave_t* enclave);

oe_result_t ecall_array_assert_all_called(oe_enclave_t* enclave);

oe_result_t ecall_basic_types(
    oe_enclave_t* enclave,
    char arg1,
    short int arg2,
    int arg3,
    float arg4,
    double arg5,
    size_t arg6,
    unsigned int arg7,
    int8_t arg8,
    int16_t arg9,
    int32_t arg10,
    int64_t arg11,
    uint8_t arg12,
    uint16_t arg13,
    uint32_t arg14,
    uint64_t arg15,
    long long arg16,
    unsigned char arg17,
    unsigned short int arg18,
    unsigned int arg19,
    unsigned long long arg20);

oe_result_t ecall_basic_non_portable_types(
    oe_enclave_t* enclave,
    wchar_t arg1,
    long int arg2,
    unsigned long int arg3,
    long double arg4);

oe_result_t get_enclave_sizeof(
    oe_enclave_t* enclave,
    uint64_t* _retval,
    type_enum_t t);

oe_result_t ecall_ret_char(
    oe_enclave_t* enclave,
    char* _retval);

oe_result_t ecall_ret_wchar_t(
    oe_enclave_t* enclave,
    wchar_t* _retval);

oe_result_t ecall_ret_short(
    oe_enclave_t* enclave,
    short int* _retval);

oe_result_t ecall_ret_int(
    oe_enclave_t* enclave,
    int* _retval);

oe_result_t ecall_ret_float(
    oe_enclave_t* enclave,
    float* _retval);

oe_result_t ecall_ret_double(
    oe_enclave_t* enclave,
    double* _retval);

oe_result_t ecall_ret_long(
    oe_enclave_t* enclave,
    long int* _retval);

oe_result_t ecall_ret_size_t(
    oe_enclave_t* enclave,
    size_t* _retval);

oe_result_t ecall_ret_unsigned(
    oe_enclave_t* enclave,
    unsigned int* _retval);

oe_result_t ecall_ret_int8_t(
    oe_enclave_t* enclave,
    int8_t* _retval);

oe_result_t ecall_ret_int16_t(
    oe_enclave_t* enclave,
    int16_t* _retval);

oe_result_t ecall_ret_int32_t(
    oe_enclave_t* enclave,
    int32_t* _retval);

oe_result_t ecall_ret_int64_t(
    oe_enclave_t* enclave,
    int64_t* _retval);

oe_result_t ecall_ret_uint8_t(
    oe_enclave_t* enclave,
    uint8_t* _retval);

oe_result_t ecall_ret_uint16_t(
    oe_enclave_t* enclave,
    uint16_t* _retval);

oe_result_t ecall_ret_uint32_t(
    oe_enclave_t* enclave,
    uint32_t* _retval);

oe_result_t ecall_ret_uint64_t(
    oe_enclave_t* enclave,
    uint64_t* _retval);

oe_result_t ecall_ret_long_long(
    oe_enclave_t* enclave,
    long long* _retval);

oe_result_t ecall_ret_unsigned_char(
    oe_enclave_t* enclave,
    unsigned char* _retval);

oe_result_t ecall_ret_unsigned_short(
    oe_enclave_t* enclave,
    unsigned short int* _retval);

oe_result_t ecall_ret_unsigned_int(
    oe_enclave_t* enclave,
    unsigned int* _retval);

oe_result_t ecall_ret_unsigned_long(
    oe_enclave_t* enclave,
    unsigned long int* _retval);

oe_result_t ecall_ret_long_double(
    oe_enclave_t* enclave,
    long double* _retval);

oe_result_t ecall_ret_unsigned_long_long(
    oe_enclave_t* enclave,
    unsigned long long* _retval);

oe_result_t ecall_ret_void(oe_enclave_t* enclave);

oe_result_t test_basic_edl_ocalls(oe_enclave_t* enclave);

oe_result_t deepcopy_value(
    oe_enclave_t* enclave,
    ShallowStruct s,
    uint64_t* ptr);

oe_result_t deepcopy_shallow(
    oe_enclave_t* enclave,
    ShallowStruct* s,
    uint64_t* ptr);

oe_result_t deepcopy_count(
    oe_enclave_t* enclave,
    CountStruct* s);

oe_result_t deepcopy_countparam(
    oe_enclave_t* enclave,
    CountParamStruct* s);

oe_result_t deepcopy_sizeparam(
    oe_enclave_t* enclave,
    SizeParamStruct* s);

oe_result_t deepcopy_countsizeparam(
    oe_enclave_t* enclave,
    CountSizeParamStruct* s);

oe_result_t deepcopy_countsizeparam_size(
    oe_enclave_t* enclave,
    CountSizeParamStruct* s);

oe_result_t deepcopy_countsizeparam_count(
    oe_enclave_t* enclave,
    CountSizeParamStruct* s);

oe_result_t deepcopy_countparamarray(
    oe_enclave_t* enclave,
    CountParamStruct* s);

oe_result_t deepcopy_sizeparamarray(
    oe_enclave_t* enclave,
    SizeParamStruct* s);

oe_result_t deepcopy_countsizeparamarray(
    oe_enclave_t* enclave,
    CountSizeParamStruct* s);

oe_result_t deepcopy_nested(
    oe_enclave_t* enclave,
    NestedStruct* n);

oe_result_t deepcopy_super_nested(
    oe_enclave_t* enclave,
    SuperNestedStruct* s,
    size_t n);

oe_result_t deepcopy_null(
    oe_enclave_t* enclave,
    CountStruct* s);

oe_result_t deepcopy_out_count(
    oe_enclave_t* enclave,
    CountStruct* s);

oe_result_t deepcopy_iovec(
    oe_enclave_t* enclave,
    IOVEC* iov,
    size_t n);

oe_result_t ecall_enum1(
    oe_enclave_t* enclave,
    Color* _retval,
    Color a1,
    Color a2[5],
    Color a3[5][5],
    Color a4[1][1][1],
    Color* a5,
    Color* a6,
    Color* a7,
    Color* a8,
    Color* a9,
    Color* a10,
    Color* a11,
    Color* a12,
    Color* a13,
    Color* a14,
    Color* a15,
    Color* a16,
    Color* a17,
    Color* a18,
    Color* a19,
    size_t count,
    size_t size);

oe_result_t test_enum_edl_ocalls(oe_enclave_t* enclave);

oe_result_t test_errno_edl_ocalls(oe_enclave_t* enclave);

oe_result_t ecall_foreign_ptr_1(
    oe_enclave_t* enclave,
    my_type1* a1,
    my_type1* a2,
    my_type1* a3);

oe_result_t ecall_foreign_ptr_2(
    oe_enclave_t* enclave,
    my_type1* a1,
    my_type1* a2,
    my_type1* a3);

oe_result_t ecall_foreign_ptr_3(
    oe_enclave_t* enclave,
    my_type1* a1,
    my_type1* a2,
    my_type1* a3);

oe_result_t ecall_foreign_ptr_4(
    oe_enclave_t* enclave,
    my_type1* a1,
    my_type1* a2,
    my_type1* a3,
    size_t count);

oe_result_t ecall_foreign_ptr_5(
    oe_enclave_t* enclave,
    my_type1* a1,
    my_type1* a2,
    my_type1* a3,
    size_t size);

oe_result_t ecall_foreign_isptr_1(
    oe_enclave_t* enclave,
    my_type2 a1,
    my_type2 a2,
    my_type2 a3);

oe_result_t ecall_foreign_isptr_2(
    oe_enclave_t* enclave,
    my_type2 a1,
    my_type2 a2,
    my_type2 a3);

oe_result_t ecall_foreign_isptr_3(
    oe_enclave_t* enclave,
    my_type2 a1,
    my_type2 a2,
    my_type2 a3);

oe_result_t ecall_foreign_isptr_4(
    oe_enclave_t* enclave,
    my_type2 a1,
    my_type2 a2,
    my_type2 a3,
    size_t count);

oe_result_t ecall_foreign_isptr_5(
    oe_enclave_t* enclave,
    my_type2 a1,
    my_type2 a2,
    my_type2 a3,
    size_t size);

oe_result_t ecall_foreign_isary(
    oe_enclave_t* enclave,
    my_type3 a1,
    my_type3 a2,
    my_type3 a3);

oe_result_t ecall_foreign_value(
    oe_enclave_t* enclave,
    my_type1* _retval,
    my_type1 a1);

oe_result_t test_foreign_edl_ocalls(oe_enclave_t* enclave);

oe_result_t ecall_pointer_char(
    oe_enclave_t* enclave,
    char** _retval,
    char* p1,
    char* p2,
    char* p3,
    char* p4,
    char* p5,
    char* p6,
    char* p7,
    char* p8,
    char* p9,
    char* p10,
    char* p11,
    char* p12,
    char* p13,
    char* p14,
    char* p15,
    char* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_wchar_t(
    oe_enclave_t* enclave,
    wchar_t** _retval,
    wchar_t* p1,
    wchar_t* p2,
    wchar_t* p3,
    wchar_t* p4,
    wchar_t* p5,
    wchar_t* p6,
    wchar_t* p7,
    wchar_t* p8,
    wchar_t* p9,
    wchar_t* p10,
    wchar_t* p11,
    wchar_t* p12,
    wchar_t* p13,
    wchar_t* p14,
    wchar_t* p15,
    wchar_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_short(
    oe_enclave_t* enclave,
    short int** _retval,
    short int* p1,
    short int* p2,
    short int* p3,
    short int* p4,
    short int* p5,
    short int* p6,
    short int* p7,
    short int* p8,
    short int* p9,
    short int* p10,
    short int* p11,
    short int* p12,
    short int* p13,
    short int* p14,
    short int* p15,
    short int* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_int(
    oe_enclave_t* enclave,
    int** _retval,
    int* p1,
    int* p2,
    int* p3,
    int* p4,
    int* p5,
    int* p6,
    int* p7,
    int* p8,
    int* p9,
    int* p10,
    int* p11,
    int* p12,
    int* p13,
    int* p14,
    int* p15,
    int* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_float(
    oe_enclave_t* enclave,
    float** _retval,
    float* p1,
    float* p2,
    float* p3,
    float* p4,
    float* p5,
    float* p6,
    float* p7,
    float* p8,
    float* p9,
    float* p10,
    float* p11,
    float* p12,
    float* p13,
    float* p14,
    float* p15,
    float* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_double(
    oe_enclave_t* enclave,
    double** _retval,
    double* p1,
    double* p2,
    double* p3,
    double* p4,
    double* p5,
    double* p6,
    double* p7,
    double* p8,
    double* p9,
    double* p10,
    double* p11,
    double* p12,
    double* p13,
    double* p14,
    double* p15,
    double* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_long(
    oe_enclave_t* enclave,
    long int** _retval,
    long int* p1,
    long int* p2,
    long int* p3,
    long int* p4,
    long int* p5,
    long int* p6,
    long int* p7,
    long int* p8,
    long int* p9,
    long int* p10,
    long int* p11,
    long int* p12,
    long int* p13,
    long int* p14,
    long int* p15,
    long int* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_size_t(
    oe_enclave_t* enclave,
    size_t** _retval,
    size_t* p1,
    size_t* p2,
    size_t* p3,
    size_t* p4,
    size_t* p5,
    size_t* p6,
    size_t* p7,
    size_t* p8,
    size_t* p9,
    size_t* p10,
    size_t* p11,
    size_t* p12,
    size_t* p13,
    size_t* p14,
    size_t* p15,
    size_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_unsigned(
    oe_enclave_t* enclave,
    unsigned int** _retval,
    unsigned int* p1,
    unsigned int* p2,
    unsigned int* p3,
    unsigned int* p4,
    unsigned int* p5,
    unsigned int* p6,
    unsigned int* p7,
    unsigned int* p8,
    unsigned int* p9,
    unsigned int* p10,
    unsigned int* p11,
    unsigned int* p12,
    unsigned int* p13,
    unsigned int* p14,
    unsigned int* p15,
    unsigned int* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_int8_t(
    oe_enclave_t* enclave,
    int8_t** _retval,
    int8_t* p1,
    int8_t* p2,
    int8_t* p3,
    int8_t* p4,
    int8_t* p5,
    int8_t* p6,
    int8_t* p7,
    int8_t* p8,
    int8_t* p9,
    int8_t* p10,
    int8_t* p11,
    int8_t* p12,
    int8_t* p13,
    int8_t* p14,
    int8_t* p15,
    int8_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_int16_t(
    oe_enclave_t* enclave,
    int16_t** _retval,
    int16_t* p1,
    int16_t* p2,
    int16_t* p3,
    int16_t* p4,
    int16_t* p5,
    int16_t* p6,
    int16_t* p7,
    int16_t* p8,
    int16_t* p9,
    int16_t* p10,
    int16_t* p11,
    int16_t* p12,
    int16_t* p13,
    int16_t* p14,
    int16_t* p15,
    int16_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_int32_t(
    oe_enclave_t* enclave,
    int32_t** _retval,
    int32_t* p1,
    int32_t* p2,
    int32_t* p3,
    int32_t* p4,
    int32_t* p5,
    int32_t* p6,
    int32_t* p7,
    int32_t* p8,
    int32_t* p9,
    int32_t* p10,
    int32_t* p11,
    int32_t* p12,
    int32_t* p13,
    int32_t* p14,
    int32_t* p15,
    int32_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_int64_t(
    oe_enclave_t* enclave,
    int64_t** _retval,
    int64_t* p1,
    int64_t* p2,
    int64_t* p3,
    int64_t* p4,
    int64_t* p5,
    int64_t* p6,
    int64_t* p7,
    int64_t* p8,
    int64_t* p9,
    int64_t* p10,
    int64_t* p11,
    int64_t* p12,
    int64_t* p13,
    int64_t* p14,
    int64_t* p15,
    int64_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_uint8_t(
    oe_enclave_t* enclave,
    uint8_t** _retval,
    uint8_t* p1,
    uint8_t* p2,
    uint8_t* p3,
    uint8_t* p4,
    uint8_t* p5,
    uint8_t* p6,
    uint8_t* p7,
    uint8_t* p8,
    uint8_t* p9,
    uint8_t* p10,
    uint8_t* p11,
    uint8_t* p12,
    uint8_t* p13,
    uint8_t* p14,
    uint8_t* p15,
    uint8_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_uint16_t(
    oe_enclave_t* enclave,
    uint16_t** _retval,
    uint16_t* p1,
    uint16_t* p2,
    uint16_t* p3,
    uint16_t* p4,
    uint16_t* p5,
    uint16_t* p6,
    uint16_t* p7,
    uint16_t* p8,
    uint16_t* p9,
    uint16_t* p10,
    uint16_t* p11,
    uint16_t* p12,
    uint16_t* p13,
    uint16_t* p14,
    uint16_t* p15,
    uint16_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_uint32_t(
    oe_enclave_t* enclave,
    uint32_t** _retval,
    uint32_t* p1,
    uint32_t* p2,
    uint32_t* p3,
    uint32_t* p4,
    uint32_t* p5,
    uint32_t* p6,
    uint32_t* p7,
    uint32_t* p8,
    uint32_t* p9,
    uint32_t* p10,
    uint32_t* p11,
    uint32_t* p12,
    uint32_t* p13,
    uint32_t* p14,
    uint32_t* p15,
    uint32_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_uint64_t(
    oe_enclave_t* enclave,
    uint64_t** _retval,
    uint64_t* p1,
    uint64_t* p2,
    uint64_t* p3,
    uint64_t* p4,
    uint64_t* p5,
    uint64_t* p6,
    uint64_t* p7,
    uint64_t* p8,
    uint64_t* p9,
    uint64_t* p10,
    uint64_t* p11,
    uint64_t* p12,
    uint64_t* p13,
    uint64_t* p14,
    uint64_t* p15,
    uint64_t* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_long_long(
    oe_enclave_t* enclave,
    long long** _retval,
    long long* p1,
    long long* p2,
    long long* p3,
    long long* p4,
    long long* p5,
    long long* p6,
    long long* p7,
    long long* p8,
    long long* p9,
    long long* p10,
    long long* p11,
    long long* p12,
    long long* p13,
    long long* p14,
    long long* p15,
    long long* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_unsigned_char(
    oe_enclave_t* enclave,
    unsigned char** _retval,
    unsigned char* p1,
    unsigned char* p2,
    unsigned char* p3,
    unsigned char* p4,
    unsigned char* p5,
    unsigned char* p6,
    unsigned char* p7,
    unsigned char* p8,
    unsigned char* p9,
    unsigned char* p10,
    unsigned char* p11,
    unsigned char* p12,
    unsigned char* p13,
    unsigned char* p14,
    unsigned char* p15,
    unsigned char* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_unsigned_short(
    oe_enclave_t* enclave,
    unsigned short int** _retval,
    unsigned short int* p1,
    unsigned short int* p2,
    unsigned short int* p3,
    unsigned short int* p4,
    unsigned short int* p5,
    unsigned short int* p6,
    unsigned short int* p7,
    unsigned short int* p8,
    unsigned short int* p9,
    unsigned short int* p10,
    unsigned short int* p11,
    unsigned short int* p12,
    unsigned short int* p13,
    unsigned short int* p14,
    unsigned short int* p15,
    unsigned short int* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_unsigned_int(
    oe_enclave_t* enclave,
    unsigned int** _retval,
    unsigned int* p1,
    unsigned int* p2,
    unsigned int* p3,
    unsigned int* p4,
    unsigned int* p5,
    unsigned int* p6,
    unsigned int* p7,
    unsigned int* p8,
    unsigned int* p9,
    unsigned int* p10,
    unsigned int* p11,
    unsigned int* p12,
    unsigned int* p13,
    unsigned int* p14,
    unsigned int* p15,
    unsigned int* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_unsigned_long(
    oe_enclave_t* enclave,
    unsigned long int** _retval,
    unsigned long int* p1,
    unsigned long int* p2,
    unsigned long int* p3,
    unsigned long int* p4,
    unsigned long int* p5,
    unsigned long int* p6,
    unsigned long int* p7,
    unsigned long int* p8,
    unsigned long int* p9,
    unsigned long int* p10,
    unsigned long int* p11,
    unsigned long int* p12,
    unsigned long int* p13,
    unsigned long int* p14,
    unsigned long int* p15,
    unsigned long int* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_unsigned_long_long(
    oe_enclave_t* enclave,
    unsigned long long** _retval,
    unsigned long long* p1,
    unsigned long long* p2,
    unsigned long long* p3,
    unsigned long long* p4,
    unsigned long long* p5,
    unsigned long long* p6,
    unsigned long long* p7,
    unsigned long long* p8,
    unsigned long long* p9,
    unsigned long long* p10,
    unsigned long long* p11,
    unsigned long long* p12,
    unsigned long long* p13,
    unsigned long long* p14,
    unsigned long long* p15,
    unsigned long long* p16,
    int pcount,
    int psize);

oe_result_t ecall_pointer_long_double(
    oe_enclave_t* enclave,
    long double** _retval,
    long double* p1,
    long double* p2,
    long double* p3,
    long double* p4,
    long double* p5,
    long double* p6,
    long double* p7,
    long double* p8,
    long double* p9,
    long double* p10,
    long double* p11,
    long double* p12,
    long double* p13,
    long double* p14,
    long double* p15,
    long double* p16,
    int pcount,
    int psize);

oe_result_t ecall_count_attribute_all_types(
    oe_enclave_t* enclave,
    int* b1,
    int* b2,
    int* b3,
    int* b4,
    int* b5,
    int* b6,
    int* b7,
    int* b8,
    int* b9,
    int* b10,
    int* b11,
    int* b12,
    int* b13,
    int* b14,
    int* b15,
    int* b16,
    int* b17,
    int* b18,
    int* b19,
    int* b20,
    int* b21,
    int* b22,
    int* b23,
    int* b24,
    char char_count,
    short int short_count,
    int int_count,
    float float_count,
    double double_count,
    long int long_count,
    size_t size_t_count,
    unsigned int unsigned_count,
    int8_t int8_t_count,
    int16_t int16_t_count,
    int32_t int32_t_count,
    int64_t int64_t_count,
    uint8_t uint8_t_count,
    uint16_t uint16_t_count,
    uint32_t uint32_t_count,
    uint64_t uint64_t_count,
    wchar_t wchar_t_count,
    long long long_long_count,
    long double long_double_count,
    unsigned char unsigned_char_count,
    unsigned short int unsigned_short_count,
    unsigned int unsigned_int_count,
    unsigned long int unsigned_long_count,
    unsigned long long unsigned_long_long_count);

oe_result_t ecall_size_attribute_all_types(
    oe_enclave_t* enclave,
    int* b1,
    int* b2,
    int* b3,
    int* b4,
    int* b5,
    int* b6,
    int* b7,
    int* b8,
    int* b9,
    int* b10,
    int* b11,
    int* b12,
    int* b13,
    int* b14,
    int* b15,
    int* b16,
    int* b17,
    int* b18,
    int* b19,
    int* b20,
    int* b21,
    int* b22,
    int* b23,
    int* b24,
    char char_size,
    short int short_size,
    int int_size,
    float float_size,
    double double_size,
    long int long_size,
    size_t size_t_size,
    unsigned int unsigned_size,
    int8_t int8_t_size,
    int16_t int16_t_size,
    int32_t int32_t_size,
    int64_t int64_t_size,
    uint8_t uint8_t_size,
    uint16_t uint16_t_size,
    uint32_t uint32_t_size,
    uint64_t uint64_t_size,
    wchar_t wchar_t_size,
    long long long_long_size,
    long double long_double_size,
    unsigned char unsigned_char_size,
    unsigned short int unsigned_short_size,
    unsigned int unsigned_int_size,
    unsigned long int unsigned_long_size,
    unsigned long long unsigned_long_long_size);

oe_result_t test_pointer_edl_ocalls(oe_enclave_t* enclave);

oe_result_t ecall_pointer_assert_all_called(oe_enclave_t* enclave);

oe_result_t ecall_string_fun1(
    oe_enclave_t* enclave,
    char* s);

oe_result_t ecall_string_fun2(
    oe_enclave_t* enclave,
    const char* s);

oe_result_t ecall_string_fun3(
    oe_enclave_t* enclave,
    char* s);

oe_result_t ecall_string_fun5(
    oe_enclave_t* enclave,
    char* s);

oe_result_t ecall_string_fun6(
    oe_enclave_t* enclave,
    const char* s);

oe_result_t ecall_string_fun7(
    oe_enclave_t* enclave,
    char* s1,
    char* s2);

oe_result_t test_string_edl_ocalls(oe_enclave_t* enclave);

oe_result_t ecall_wstring_fun1(
    oe_enclave_t* enclave,
    wchar_t* s);

oe_result_t ecall_wstring_fun2(
    oe_enclave_t* enclave,
    const wchar_t* s);

oe_result_t ecall_wstring_fun3(
    oe_enclave_t* enclave,
    wchar_t* s);

oe_result_t ecall_wstring_fun5(
    oe_enclave_t* enclave,
    wchar_t* s);

oe_result_t ecall_wstring_fun6(
    oe_enclave_t* enclave,
    const wchar_t* s);

oe_result_t ecall_wstring_fun7(
    oe_enclave_t* enclave,
    wchar_t* s1,
    wchar_t* s2);

oe_result_t test_wstring_edl_ocalls(oe_enclave_t* enclave);

oe_result_t ecall_string_no_null_terminator(
    oe_enclave_t* enclave,
    char* s1,
    char* s2);

oe_result_t ecall_wstring_no_null_terminator(
    oe_enclave_t* enclave,
    wchar_t* s1,
    wchar_t* s2);

oe_result_t ecall_struct1(
    oe_enclave_t* enclave,
    MyStruct1* _retval,
    MyStruct1 a1,
    MyStruct1 a2[5],
    MyStruct1 a3[5][5],
    MyStruct1 a4[1][1][1],
    MyStruct1* a5,
    MyStruct1* a6,
    MyStruct1* a7,
    MyStruct1* a8,
    MyStruct1* a9,
    MyStruct1* a10,
    MyStruct1* a11,
    MyStruct1* a12,
    MyStruct1* a13,
    MyStruct1* a14,
    MyStruct1* a15,
    MyStruct1* a16,
    MyStruct1* a17,
    MyStruct1* a18,
    MyStruct1* a19,
    size_t count,
    size_t size);

oe_result_t test_struct_edl_ocalls(oe_enclave_t* enclave);

oe_result_t ecall_sum(
    oe_enclave_t* enclave,
    int* _retval,
    int a,
    int b);

oe_result_t switchless_ecall_sum(
    oe_enclave_t* enclave,
    int* _retval,
    int a,
    int b);

oe_result_t test_switchless_edl_ocalls(oe_enclave_t* enclave);

oe_result_t enc_foo1(oe_enclave_t* enclave);

/**** OCALL prototypes. ****/
void ocall_array_char(
    char a1[2],
    char a2[2][2],
    char a3[3][3],
    char a4[4][4]);

void ocall_array_wchar_t(
    wchar_t a1[2],
    wchar_t a2[2][2],
    wchar_t a3[3][3],
    wchar_t a4[4][4]);

void ocall_array_short(
    short int a1[2],
    short int a2[2][2],
    short int a3[3][3],
    short int a4[4][4]);

void ocall_array_int(
    int a1[2],
    int a2[2][2],
    int a3[3][3],
    int a4[4][4]);

void ocall_array_float(
    float a1[2],
    float a2[2][2],
    float a3[3][3],
    float a4[4][4]);

void ocall_array_double(
    double a1[2],
    double a2[2][2],
    double a3[3][3],
    double a4[4][4]);

void ocall_array_long(
    long int a1[2],
    long int a2[2][2],
    long int a3[3][3],
    long int a4[4][4]);

void ocall_array_size_t(
    size_t a1[2],
    size_t a2[2][2],
    size_t a3[3][3],
    size_t a4[4][4]);

void ocall_array_unsigned(
    unsigned int a1[2],
    unsigned int a2[2][2],
    unsigned int a3[3][3],
    unsigned int a4[4][4]);

void ocall_array_int8_t(
    int8_t a1[2],
    int8_t a2[2][2],
    int8_t a3[3][3],
    int8_t a4[4][4]);

void ocall_array_int16_t(
    int16_t a1[2],
    int16_t a2[2][2],
    int16_t a3[3][3],
    int16_t a4[4][4]);

void ocall_array_int32_t(
    int32_t a1[2],
    int32_t a2[2][2],
    int32_t a3[3][3],
    int32_t a4[4][4]);

void ocall_array_int64_t(
    int64_t a1[2],
    int64_t a2[2][2],
    int64_t a3[3][3],
    int64_t a4[4][4]);

void ocall_array_uint8_t(
    uint8_t a1[2],
    uint8_t a2[2][2],
    uint8_t a3[3][3],
    uint8_t a4[4][4]);

void ocall_array_uint16_t(
    uint16_t a1[2],
    uint16_t a2[2][2],
    uint16_t a3[3][3],
    uint16_t a4[4][4]);

void ocall_array_uint32_t(
    uint32_t a1[2],
    uint32_t a2[2][2],
    uint32_t a3[3][3],
    uint32_t a4[4][4]);

void ocall_array_uint64_t(
    uint64_t a1[2],
    uint64_t a2[2][2],
    uint64_t a3[3][3],
    uint64_t a4[4][4]);

void ocall_array_long_long(
    long long a1[2],
    long long a2[2][2],
    long long a3[3][3],
    long long a4[4][4]);

void ocall_array_unsigned_char(
    unsigned char a1[2],
    unsigned char a2[2][2],
    unsigned char a3[3][3],
    unsigned char a4[4][4]);

void ocall_array_unsigned_short(
    unsigned short int a1[2],
    unsigned short int a2[2][2],
    unsigned short int a3[3][3],
    unsigned short int a4[4][4]);

void ocall_array_unsigned_int(
    unsigned int a1[2],
    unsigned int a2[2][2],
    unsigned int a3[3][3],
    unsigned int a4[4][4]);

void ocall_array_unsigned_long(
    unsigned long int a1[2],
    unsigned long int a2[2][2],
    unsigned long int a3[3][3],
    unsigned long int a4[4][4]);

void ocall_array_unsigned_long_long(
    unsigned long long a1[2],
    unsigned long long a2[2][2],
    unsigned long long a3[3][3],
    unsigned long long a4[4][4]);

void ocall_array_long_double(
    long double a1[2],
    long double a2[2][2],
    long double a3[3][3],
    long double a4[4][4]);

void ocall_array_assert_all_called(void);

void ocall_basic_types(
    char arg1,
    short int arg2,
    int arg3,
    float arg4,
    double arg5,
    size_t arg6,
    unsigned int arg7,
    int8_t arg8,
    int16_t arg9,
    int32_t arg10,
    int64_t arg11,
    uint8_t arg12,
    uint16_t arg13,
    uint32_t arg14,
    uint64_t arg15,
    long long arg16,
    unsigned char arg17,
    unsigned short int arg18,
    unsigned int arg19,
    unsigned long long arg20);

void ocall_basic_non_portable_types(
    wchar_t arg1,
    long int arg2,
    unsigned long int arg3,
    long double arg4);

uint64_t get_host_sizeof(type_enum_t t);

char ocall_ret_char(void);

wchar_t ocall_ret_wchar_t(void);

short int ocall_ret_short(void);

int ocall_ret_int(void);

float ocall_ret_float(void);

double ocall_ret_double(void);

long int ocall_ret_long(void);

size_t ocall_ret_size_t(void);

unsigned int ocall_ret_unsigned(void);

int8_t ocall_ret_int8_t(void);

int16_t ocall_ret_int16_t(void);

int32_t ocall_ret_int32_t(void);

int64_t ocall_ret_int64_t(void);

uint8_t ocall_ret_uint8_t(void);

uint16_t ocall_ret_uint16_t(void);

uint32_t ocall_ret_uint32_t(void);

uint64_t ocall_ret_uint64_t(void);

long long ocall_ret_long_long(void);

unsigned char ocall_ret_unsigned_char(void);

unsigned short int ocall_ret_unsigned_short(void);

unsigned int ocall_ret_unsigned_int(void);

unsigned long int ocall_ret_unsigned_long(void);

long double ocall_ret_long_double(void);

unsigned long long ocall_ret_unsigned_long_long(void);

void ocall_ret_void(void);

Color ocall_enum1(
    Color a1,
    Color a2[5],
    Color a3[5][5],
    Color a4[1][1][1],
    Color* a5,
    Color* a6,
    Color* a7,
    Color* a8,
    Color* a9,
    Color* a10,
    Color* a11,
    Color* a12,
    Color* a13,
    Color* a14,
    Color* a15,
    Color* a16,
    Color* a17,
    Color* a18,
    Color* a19,
    size_t count,
    size_t size);

void ocall_errno(void);

void ocall_set_host_errno(int e);

void ocall_noop(void);

void ocall_foreign_ptr_1(
    my_type1* a1,
    my_type1* a2,
    my_type1* a3);

void ocall_foreign_ptr_2(
    my_type1* a1,
    my_type1* a2,
    my_type1* a3);

void ocall_foreign_ptr_3(
    my_type1* a1,
    my_type1* a2,
    my_type1* a3);

void ocall_foreign_ptr_4(
    my_type1* a1,
    my_type1* a2,
    my_type1* a3,
    size_t count);

void ocall_foreign_ptr_5(
    my_type1* a1,
    my_type1* a2,
    my_type1* a3,
    size_t size);

void ocall_foreign_isptr_1(
    my_type2 a1,
    my_type2 a2,
    my_type2 a3);

void ocall_foreign_isptr_2(
    my_type2 a1,
    my_type2 a2,
    my_type2 a3);

void ocall_foreign_isptr_3(
    my_type2 a1,
    my_type2 a2,
    my_type2 a3);

void ocall_foreign_isptr_4(
    my_type2 a1,
    my_type2 a2,
    my_type2 a3,
    size_t count);

void ocall_foreign_isptr_5(
    my_type2 a1,
    my_type2 a2,
    my_type2 a3,
    size_t size);

void ocall_foreign_isary(
    my_type3 a1,
    my_type3 a2,
    my_type3 a3);

my_type1 ocall_foreign_value(my_type1 a1);

char* ocall_pointer_char(
    char* p1,
    char* p2,
    char* p3,
    char* p4,
    char* p5,
    char* p6,
    char* p7,
    char* p8,
    char* p9,
    char* p10,
    char* p11,
    char* p12,
    char* p13,
    char* p14,
    char* p15,
    char* p16,
    int pcount,
    int psize);

wchar_t* ocall_pointer_wchar_t(
    wchar_t* p1,
    wchar_t* p2,
    wchar_t* p3,
    wchar_t* p4,
    wchar_t* p5,
    wchar_t* p6,
    wchar_t* p7,
    wchar_t* p8,
    wchar_t* p9,
    wchar_t* p10,
    wchar_t* p11,
    wchar_t* p12,
    wchar_t* p13,
    wchar_t* p14,
    wchar_t* p15,
    wchar_t* p16,
    int pcount,
    int psize);

short int* ocall_pointer_short(
    short int* p1,
    short int* p2,
    short int* p3,
    short int* p4,
    short int* p5,
    short int* p6,
    short int* p7,
    short int* p8,
    short int* p9,
    short int* p10,
    short int* p11,
    short int* p12,
    short int* p13,
    short int* p14,
    short int* p15,
    short int* p16,
    int pcount,
    int psize);

int* ocall_pointer_int(
    int* p1,
    int* p2,
    int* p3,
    int* p4,
    int* p5,
    int* p6,
    int* p7,
    int* p8,
    int* p9,
    int* p10,
    int* p11,
    int* p12,
    int* p13,
    int* p14,
    int* p15,
    int* p16,
    int pcount,
    int psize);

float* ocall_pointer_float(
    float* p1,
    float* p2,
    float* p3,
    float* p4,
    float* p5,
    float* p6,
    float* p7,
    float* p8,
    float* p9,
    float* p10,
    float* p11,
    float* p12,
    float* p13,
    float* p14,
    float* p15,
    float* p16,
    int pcount,
    int psize);

double* ocall_pointer_double(
    double* p1,
    double* p2,
    double* p3,
    double* p4,
    double* p5,
    double* p6,
    double* p7,
    double* p8,
    double* p9,
    double* p10,
    double* p11,
    double* p12,
    double* p13,
    double* p14,
    double* p15,
    double* p16,
    int pcount,
    int psize);

long int* ocall_pointer_long(
    long int* p1,
    long int* p2,
    long int* p3,
    long int* p4,
    long int* p5,
    long int* p6,
    long int* p7,
    long int* p8,
    long int* p9,
    long int* p10,
    long int* p11,
    long int* p12,
    long int* p13,
    long int* p14,
    long int* p15,
    long int* p16,
    int pcount,
    int psize);

size_t* ocall_pointer_size_t(
    size_t* p1,
    size_t* p2,
    size_t* p3,
    size_t* p4,
    size_t* p5,
    size_t* p6,
    size_t* p7,
    size_t* p8,
    size_t* p9,
    size_t* p10,
    size_t* p11,
    size_t* p12,
    size_t* p13,
    size_t* p14,
    size_t* p15,
    size_t* p16,
    int pcount,
    int psize);

unsigned int* ocall_pointer_unsigned(
    unsigned int* p1,
    unsigned int* p2,
    unsigned int* p3,
    unsigned int* p4,
    unsigned int* p5,
    unsigned int* p6,
    unsigned int* p7,
    unsigned int* p8,
    unsigned int* p9,
    unsigned int* p10,
    unsigned int* p11,
    unsigned int* p12,
    unsigned int* p13,
    unsigned int* p14,
    unsigned int* p15,
    unsigned int* p16,
    int pcount,
    int psize);

int8_t* ocall_pointer_int8_t(
    int8_t* p1,
    int8_t* p2,
    int8_t* p3,
    int8_t* p4,
    int8_t* p5,
    int8_t* p6,
    int8_t* p7,
    int8_t* p8,
    int8_t* p9,
    int8_t* p10,
    int8_t* p11,
    int8_t* p12,
    int8_t* p13,
    int8_t* p14,
    int8_t* p15,
    int8_t* p16,
    int pcount,
    int psize);

int16_t* ocall_pointer_int16_t(
    int16_t* p1,
    int16_t* p2,
    int16_t* p3,
    int16_t* p4,
    int16_t* p5,
    int16_t* p6,
    int16_t* p7,
    int16_t* p8,
    int16_t* p9,
    int16_t* p10,
    int16_t* p11,
    int16_t* p12,
    int16_t* p13,
    int16_t* p14,
    int16_t* p15,
    int16_t* p16,
    int pcount,
    int psize);

int32_t* ocall_pointer_int32_t(
    int32_t* p1,
    int32_t* p2,
    int32_t* p3,
    int32_t* p4,
    int32_t* p5,
    int32_t* p6,
    int32_t* p7,
    int32_t* p8,
    int32_t* p9,
    int32_t* p10,
    int32_t* p11,
    int32_t* p12,
    int32_t* p13,
    int32_t* p14,
    int32_t* p15,
    int32_t* p16,
    int pcount,
    int psize);

int64_t* ocall_pointer_int64_t(
    int64_t* p1,
    int64_t* p2,
    int64_t* p3,
    int64_t* p4,
    int64_t* p5,
    int64_t* p6,
    int64_t* p7,
    int64_t* p8,
    int64_t* p9,
    int64_t* p10,
    int64_t* p11,
    int64_t* p12,
    int64_t* p13,
    int64_t* p14,
    int64_t* p15,
    int64_t* p16,
    int pcount,
    int psize);

uint8_t* ocall_pointer_uint8_t(
    uint8_t* p1,
    uint8_t* p2,
    uint8_t* p3,
    uint8_t* p4,
    uint8_t* p5,
    uint8_t* p6,
    uint8_t* p7,
    uint8_t* p8,
    uint8_t* p9,
    uint8_t* p10,
    uint8_t* p11,
    uint8_t* p12,
    uint8_t* p13,
    uint8_t* p14,
    uint8_t* p15,
    uint8_t* p16,
    int pcount,
    int psize);

uint16_t* ocall_pointer_uint16_t(
    uint16_t* p1,
    uint16_t* p2,
    uint16_t* p3,
    uint16_t* p4,
    uint16_t* p5,
    uint16_t* p6,
    uint16_t* p7,
    uint16_t* p8,
    uint16_t* p9,
    uint16_t* p10,
    uint16_t* p11,
    uint16_t* p12,
    uint16_t* p13,
    uint16_t* p14,
    uint16_t* p15,
    uint16_t* p16,
    int pcount,
    int psize);

uint32_t* ocall_pointer_uint32_t(
    uint32_t* p1,
    uint32_t* p2,
    uint32_t* p3,
    uint32_t* p4,
    uint32_t* p5,
    uint32_t* p6,
    uint32_t* p7,
    uint32_t* p8,
    uint32_t* p9,
    uint32_t* p10,
    uint32_t* p11,
    uint32_t* p12,
    uint32_t* p13,
    uint32_t* p14,
    uint32_t* p15,
    uint32_t* p16,
    int pcount,
    int psize);

uint64_t* ocall_pointer_uint64_t(
    uint64_t* p1,
    uint64_t* p2,
    uint64_t* p3,
    uint64_t* p4,
    uint64_t* p5,
    uint64_t* p6,
    uint64_t* p7,
    uint64_t* p8,
    uint64_t* p9,
    uint64_t* p10,
    uint64_t* p11,
    uint64_t* p12,
    uint64_t* p13,
    uint64_t* p14,
    uint64_t* p15,
    uint64_t* p16,
    int pcount,
    int psize);

long long* ocall_pointer_long_long(
    long long* p1,
    long long* p2,
    long long* p3,
    long long* p4,
    long long* p5,
    long long* p6,
    long long* p7,
    long long* p8,
    long long* p9,
    long long* p10,
    long long* p11,
    long long* p12,
    long long* p13,
    long long* p14,
    long long* p15,
    long long* p16,
    int pcount,
    int psize);

unsigned char* ocall_pointer_unsigned_char(
    unsigned char* p1,
    unsigned char* p2,
    unsigned char* p3,
    unsigned char* p4,
    unsigned char* p5,
    unsigned char* p6,
    unsigned char* p7,
    unsigned char* p8,
    unsigned char* p9,
    unsigned char* p10,
    unsigned char* p11,
    unsigned char* p12,
    unsigned char* p13,
    unsigned char* p14,
    unsigned char* p15,
    unsigned char* p16,
    int pcount,
    int psize);

unsigned short int* ocall_pointer_unsigned_short(
    unsigned short int* p1,
    unsigned short int* p2,
    unsigned short int* p3,
    unsigned short int* p4,
    unsigned short int* p5,
    unsigned short int* p6,
    unsigned short int* p7,
    unsigned short int* p8,
    unsigned short int* p9,
    unsigned short int* p10,
    unsigned short int* p11,
    unsigned short int* p12,
    unsigned short int* p13,
    unsigned short int* p14,
    unsigned short int* p15,
    unsigned short int* p16,
    int pcount,
    int psize);

unsigned int* ocall_pointer_unsigned_int(
    unsigned int* p1,
    unsigned int* p2,
    unsigned int* p3,
    unsigned int* p4,
    unsigned int* p5,
    unsigned int* p6,
    unsigned int* p7,
    unsigned int* p8,
    unsigned int* p9,
    unsigned int* p10,
    unsigned int* p11,
    unsigned int* p12,
    unsigned int* p13,
    unsigned int* p14,
    unsigned int* p15,
    unsigned int* p16,
    int pcount,
    int psize);

unsigned long int* ocall_pointer_unsigned_long(
    unsigned long int* p1,
    unsigned long int* p2,
    unsigned long int* p3,
    unsigned long int* p4,
    unsigned long int* p5,
    unsigned long int* p6,
    unsigned long int* p7,
    unsigned long int* p8,
    unsigned long int* p9,
    unsigned long int* p10,
    unsigned long int* p11,
    unsigned long int* p12,
    unsigned long int* p13,
    unsigned long int* p14,
    unsigned long int* p15,
    unsigned long int* p16,
    int pcount,
    int psize);

unsigned long long* ocall_pointer_unsigned_long_long(
    unsigned long long* p1,
    unsigned long long* p2,
    unsigned long long* p3,
    unsigned long long* p4,
    unsigned long long* p5,
    unsigned long long* p6,
    unsigned long long* p7,
    unsigned long long* p8,
    unsigned long long* p9,
    unsigned long long* p10,
    unsigned long long* p11,
    unsigned long long* p12,
    unsigned long long* p13,
    unsigned long long* p14,
    unsigned long long* p15,
    unsigned long long* p16,
    int pcount,
    int psize);

long double* ocall_pointer_long_double(
    long double* p1,
    long double* p2,
    long double* p3,
    long double* p4,
    long double* p5,
    long double* p6,
    long double* p7,
    long double* p8,
    long double* p9,
    long double* p10,
    long double* p11,
    long double* p12,
    long double* p13,
    long double* p14,
    long double* p15,
    long double* p16,
    int pcount,
    int psize);

void ocall_count_attribute_all_types(
    int* b1,
    int* b2,
    int* b3,
    int* b4,
    int* b5,
    int* b6,
    int* b7,
    int* b8,
    int* b9,
    int* b10,
    int* b11,
    int* b12,
    int* b13,
    int* b14,
    int* b15,
    int* b16,
    int* b17,
    int* b18,
    int* b19,
    int* b20,
    int* b21,
    int* b22,
    int* b23,
    int* b24,
    char char_count,
    short int short_count,
    int int_count,
    float float_count,
    double double_count,
    long int long_count,
    size_t size_t_count,
    unsigned int unsigned_count,
    int8_t int8_t_count,
    int16_t int16_t_count,
    int32_t int32_t_count,
    int64_t int64_t_count,
    uint8_t uint8_t_count,
    uint16_t uint16_t_count,
    uint32_t uint32_t_count,
    uint64_t uint64_t_count,
    wchar_t wchar_t_count,
    long long long_long_count,
    long double long_double_count,
    unsigned char unsigned_char_count,
    unsigned short int unsigned_short_count,
    unsigned int unsigned_int_count,
    unsigned long int unsigned_long_count,
    unsigned long long unsigned_long_long_count);

void ocall_size_attribute_all_types(
    int* b1,
    int* b2,
    int* b3,
    int* b4,
    int* b5,
    int* b6,
    int* b7,
    int* b8,
    int* b9,
    int* b10,
    int* b11,
    int* b12,
    int* b13,
    int* b14,
    int* b15,
    int* b16,
    int* b17,
    int* b18,
    int* b19,
    int* b20,
    int* b21,
    int* b22,
    int* b23,
    int* b24,
    char char_size,
    short int short_size,
    int int_size,
    float float_size,
    double double_size,
    long int long_size,
    size_t size_t_size,
    unsigned int unsigned_size,
    int8_t int8_t_size,
    int16_t int16_t_size,
    int32_t int32_t_size,
    int64_t int64_t_size,
    uint8_t uint8_t_size,
    uint16_t uint16_t_size,
    uint32_t uint32_t_size,
    uint64_t uint64_t_size,
    wchar_t wchar_t_size,
    long long long_long_size,
    long double long_double_size,
    unsigned char unsigned_char_size,
    unsigned short int unsigned_short_size,
    unsigned int unsigned_int_size,
    unsigned long int unsigned_long_size,
    unsigned long long unsigned_long_long_size);

void ocall_pointer_assert_all_called(void);

void ocall_string_fun1(char* s);

void ocall_string_fun2(const char* s);

void ocall_string_fun3(char* s);

void ocall_string_fun5(char* s);

void ocall_string_fun6(const char* s);

void ocall_string_fun7(
    char* s1,
    char* s2);

void ocall_wstring_fun1(wchar_t* s);

void ocall_wstring_fun2(const wchar_t* s);

void ocall_wstring_fun3(wchar_t* s);

void ocall_wstring_fun5(wchar_t* s);

void ocall_wstring_fun6(const wchar_t* s);

void ocall_wstring_fun7(
    wchar_t* s1,
    wchar_t* s2);

void ocall_string_no_null_terminator(
    bool erasenull,
    char* s);

void ocall_wstring_no_null_terminator(
    bool erasenull,
    wchar_t* s);

MyStruct1 ocall_struct1(
    MyStruct1 a1,
    MyStruct1 a2[5],
    MyStruct1 a3[5][5],
    MyStruct1 a4[1][1][1],
    MyStruct1* a5,
    MyStruct1* a6,
    MyStruct1* a7,
    MyStruct1* a8,
    MyStruct1* a9,
    MyStruct1* a10,
    MyStruct1* a11,
    MyStruct1* a12,
    MyStruct1* a13,
    MyStruct1* a14,
    MyStruct1* a15,
    MyStruct1* a16,
    MyStruct1* a17,
    MyStruct1* a18,
    MyStruct1* a19,
    size_t count,
    size_t size);

int ocall_sum(
    int a,
    int b);

int switchless_ocall_sum(
    int a,
    int b);

void host_foo1(void);

OE_EXTERNC_END

#endif // EDGER8R_ALL_U_H
