/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_OTHER_ARGS_H
#define EDGER8R_OTHER_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
typedef struct MyOther
{
    int x;
} MyOther;

/**** ECALL marshalling structs. ****/
typedef struct _ecall_other_args_t
{
    oe_result_t _result;
    MyOther _retval;
    MyOther o;
} ecall_other_args_t;

typedef struct _test_other_edl_ocalls_args_t
{
    oe_result_t _result;
} test_other_edl_ocalls_args_t;

/**** OCALL marshalling structs. ****/
typedef struct _ocall_other_args_t
{
    oe_result_t _result;
    MyOther _retval;
    MyOther o;
} ocall_other_args_t;

/**** Trusted function IDs ****/
enum
{
    other_fcn_id_ecall_other = 0,
    other_fcn_id_test_other_edl_ocalls = 1,
    other_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{
    other_fcn_id_ocall_other = 0,
    other_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_OTHER_ARGS_H
