/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ECHO_ARGS_H
#define EDGER8R_ECHO_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _enc_echo_args_t
{
    oe_result_t _result;
    int _retval;
    char* in;
    size_t in_len;
    char* out;
} enc_echo_args_t;

/**** OCALL marshalling structs. ****/
typedef struct _host_echo_args_t
{
    oe_result_t _result;
    int _retval;
    char* in;
    size_t in_len;
    char* out;
    char* str1;
    size_t str1_len;
    char* str2;
    char* str3;
} host_echo_args_t;

/**** Trusted function IDs ****/
enum
{
    echo_fcn_id_enc_echo = 0,
    echo_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{
    echo_fcn_id_host_echo = 0,
    echo_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_ECHO_ARGS_H
