/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_MIXED_ARGS_H
#define EDGER8R_MIXED_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _foo_c_args_t
{
    oe_result_t _result;
    int a;
} foo_c_args_t;

typedef struct _foo_cpp_args_t
{
    oe_result_t _result;
    int b;
} foo_cpp_args_t;

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** Trusted function IDs ****/
enum
{
    mixed_fcn_id_foo_c = 0,
    mixed_fcn_id_foo_cpp = 1,
    mixed_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{

    mixed_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_MIXED_ARGS_H
