/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SAFECRT_ARGS_H
#define EDGER8R_SAFECRT_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _enc_test_memcpy_s_args_t
{
    oe_result_t _result;
} enc_test_memcpy_s_args_t;

typedef struct _enc_test_memmove_s_args_t
{
    oe_result_t _result;
} enc_test_memmove_s_args_t;

typedef struct _enc_test_strncpy_s_args_t
{
    oe_result_t _result;
} enc_test_strncpy_s_args_t;

typedef struct _enc_test_strncat_s_args_t
{
    oe_result_t _result;
} enc_test_strncat_s_args_t;

typedef struct _enc_test_memset_s_args_t
{
    oe_result_t _result;
} enc_test_memset_s_args_t;

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** Trusted function IDs ****/
enum
{
    safecrt_fcn_id_enc_test_memcpy_s = 0,
    safecrt_fcn_id_enc_test_memmove_s = 1,
    safecrt_fcn_id_enc_test_strncpy_s = 2,
    safecrt_fcn_id_enc_test_strncat_s = 3,
    safecrt_fcn_id_enc_test_memset_s = 4,
    safecrt_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{

    safecrt_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_SAFECRT_ARGS_H
