/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_TESTS_ARGS_H
#define EDGER8R_TESTS_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
#include "includes.h"

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _test_iso8601_time_args_t
{
    oe_result_t _result;
} test_iso8601_time_args_t;

typedef struct _test_iso8601_time_negative_args_t
{
    oe_result_t _result;
} test_iso8601_time_negative_args_t;

typedef struct _test_verify_tcb_info_args_t
{
    oe_result_t _result;
    oe_result_t _retval;
    char* tcb_info;
    size_t tcb_info_len;
    oe_tcb_level_t* platform_tcb_level;
    oe_parsed_tcb_info_t* parsed_tcb_info;
} test_verify_tcb_info_args_t;

typedef struct _test_minimum_issue_date_args_t
{
    oe_result_t _result;
    oe_datetime_t now;
} test_minimum_issue_date_args_t;

typedef struct _enclave_test_local_report_args_t
{
    oe_result_t _result;
    sgx_target_info_t* target_info;
} enclave_test_local_report_args_t;

typedef struct _enclave_test_remote_report_args_t
{
    oe_result_t _result;
} enclave_test_remote_report_args_t;

typedef struct _enclave_test_parse_report_negative_args_t
{
    oe_result_t _result;
} enclave_test_parse_report_negative_args_t;

typedef struct _enclave_test_local_verify_report_args_t
{
    oe_result_t _result;
} enclave_test_local_verify_report_args_t;

typedef struct _enclave_test_remote_verify_report_args_t
{
    oe_result_t _result;
} enclave_test_remote_verify_report_args_t;

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** Trusted function IDs ****/
enum
{
    tests_fcn_id_test_iso8601_time = 0,
    tests_fcn_id_test_iso8601_time_negative = 1,
    tests_fcn_id_test_verify_tcb_info = 2,
    tests_fcn_id_test_minimum_issue_date = 3,
    tests_fcn_id_enclave_test_local_report = 4,
    tests_fcn_id_enclave_test_remote_report = 5,
    tests_fcn_id_enclave_test_parse_report_negative = 6,
    tests_fcn_id_enclave_test_local_verify_report = 7,
    tests_fcn_id_enclave_test_remote_verify_report = 8,
    tests_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{

    tests_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_TESTS_ARGS_H
