/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_CRYPTO_CRLS_CERT_CHAINS_U_H
#define EDGER8R_CRYPTO_CRLS_CERT_CHAINS_U_H

#include <openenclave/host.h>

#include "crypto_crls_cert_chains_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_crypto_crls_cert_chains_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
#ifdef OE_CONTEXT_SWITCHLESS_EXPERIMENTAL_FEATURE
    const oe_enclave_config_t* configs,
    uint32_t config_count,
#else
    const void* config,
    uint32_t config_size,
#endif
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t ecall_test_cert_chain_positive(
    oe_enclave_t* enclave,
    const char* root,
    const char* intermediate,
    const char* leaf,
    const char* leaf2);

oe_result_t ecall_test_cert_chain_negative(
    oe_enclave_t* enclave,
    const char* root,
    const char* intermediate,
    const char* leaf,
    const char* leaf2);

oe_result_t ecall_test_crls(
    oe_enclave_t* enclave,
    const char* root,
    const char* intermediate,
    const char* leaf1,
    const char* leaf2,
    const char* root_crl1,
    size_t root_crl1_size,
    const char* root_crl2,
    size_t root_crl2_size,
    const char* intermediate_crl1,
    size_t intermediate_crl1_size,
    const char* intermediate_crl2,
    size_t intermediate_crl2_size);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_CRYPTO_CRLS_CERT_CHAINS_U_H
