/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "crypto_crls_cert_chains_u.h"

#include <openenclave/edger8r/host.h>

#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN

/**** ECALL function wrappers. ****/

oe_result_t ecall_test_cert_chain_positive(
    oe_enclave_t* enclave,
    const char* root,
    const char* intermediate,
    const char* leaf,
    const char* leaf2)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshalling struct. */
    ecall_test_cert_chain_positive_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Deep copy buffer. */
    /* No pointers to save for deep copy. */

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.root = (char*)root;
    _args.root_len = (root) ? (strlen(root) + 1) : 0;
    _args.intermediate = (char*)intermediate;
    _args.intermediate_len = (intermediate) ? (strlen(intermediate) + 1) : 0;
    _args.leaf = (char*)leaf;
    _args.leaf_len = (leaf) ? (strlen(leaf) + 1) : 0;
    _args.leaf2 = (char*)leaf2;
    _args.leaf2_len = (leaf2) ? (strlen(leaf2) + 1) : 0;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_test_cert_chain_positive_args_t));
    if (root)
        OE_ADD_SIZE(_input_buffer_size, _args.root_len * sizeof(char));
    if (intermediate)
        OE_ADD_SIZE(_input_buffer_size, _args.intermediate_len * sizeof(char));
    if (leaf)
        OE_ADD_SIZE(_input_buffer_size, _args.leaf_len * sizeof(char));
    if (leaf2)
        OE_ADD_SIZE(_input_buffer_size, _args.leaf2_len * sizeof(char));
    
    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_test_cert_chain_positive_args_t));
    /* There were no corresponding parameters. */
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (ecall_test_cert_chain_positive_args_t*)_input_buffer;
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    if (root)
        OE_WRITE_IN_PARAM(root, _args.root_len * sizeof(char), char*);
    if (intermediate)
        OE_WRITE_IN_PARAM(intermediate, _args.intermediate_len * sizeof(char), char*);
    if (leaf)
        OE_WRITE_IN_PARAM(leaf, _args.leaf_len * sizeof(char), char*);
    if (leaf2)
        OE_WRITE_IN_PARAM(leaf2, _args.leaf2_len * sizeof(char), char*);
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function. */
    if ((_result = oe_call_enclave_function(
             enclave,
             crypto_crls_cert_chains_fcn_id_ecall_test_cert_chain_positive,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size,
             &_output_bytes_written)) != OE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (ecall_test_cert_chain_positive_args_t*)_output_buffer;
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Check if the call succeeded. */
    if ((_result = _pargs_out->_result) != OE_OK)
        goto done;
    
    /* Currently exactly _output_buffer_size bytes must be written. */
    if (_output_bytes_written != _output_buffer_size)
    {
        _result = OE_FAILURE;
        goto done;
    }
    
    /* Unmarshal return value and out, in-out parameters. */
    /* No return value. */
    /* No pointers to restore for deep copy. */
    /* There were no out nor in-out parameters. */

    _result = OE_OK;

done:
    if (_buffer)
        free(_buffer);

    /* No `_ptrs` to free for deep copy. */

    return _result;
}

oe_result_t ecall_test_cert_chain_negative(
    oe_enclave_t* enclave,
    const char* root,
    const char* intermediate,
    const char* leaf,
    const char* leaf2)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshalling struct. */
    ecall_test_cert_chain_negative_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Deep copy buffer. */
    /* No pointers to save for deep copy. */

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.root = (char*)root;
    _args.root_len = (root) ? (strlen(root) + 1) : 0;
    _args.intermediate = (char*)intermediate;
    _args.intermediate_len = (intermediate) ? (strlen(intermediate) + 1) : 0;
    _args.leaf = (char*)leaf;
    _args.leaf_len = (leaf) ? (strlen(leaf) + 1) : 0;
    _args.leaf2 = (char*)leaf2;
    _args.leaf2_len = (leaf2) ? (strlen(leaf2) + 1) : 0;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_test_cert_chain_negative_args_t));
    if (root)
        OE_ADD_SIZE(_input_buffer_size, _args.root_len * sizeof(char));
    if (intermediate)
        OE_ADD_SIZE(_input_buffer_size, _args.intermediate_len * sizeof(char));
    if (leaf)
        OE_ADD_SIZE(_input_buffer_size, _args.leaf_len * sizeof(char));
    if (leaf2)
        OE_ADD_SIZE(_input_buffer_size, _args.leaf2_len * sizeof(char));
    
    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_test_cert_chain_negative_args_t));
    /* There were no corresponding parameters. */
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (ecall_test_cert_chain_negative_args_t*)_input_buffer;
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    if (root)
        OE_WRITE_IN_PARAM(root, _args.root_len * sizeof(char), char*);
    if (intermediate)
        OE_WRITE_IN_PARAM(intermediate, _args.intermediate_len * sizeof(char), char*);
    if (leaf)
        OE_WRITE_IN_PARAM(leaf, _args.leaf_len * sizeof(char), char*);
    if (leaf2)
        OE_WRITE_IN_PARAM(leaf2, _args.leaf2_len * sizeof(char), char*);
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function. */
    if ((_result = oe_call_enclave_function(
             enclave,
             crypto_crls_cert_chains_fcn_id_ecall_test_cert_chain_negative,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size,
             &_output_bytes_written)) != OE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (ecall_test_cert_chain_negative_args_t*)_output_buffer;
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Check if the call succeeded. */
    if ((_result = _pargs_out->_result) != OE_OK)
        goto done;
    
    /* Currently exactly _output_buffer_size bytes must be written. */
    if (_output_bytes_written != _output_buffer_size)
    {
        _result = OE_FAILURE;
        goto done;
    }
    
    /* Unmarshal return value and out, in-out parameters. */
    /* No return value. */
    /* No pointers to restore for deep copy. */
    /* There were no out nor in-out parameters. */

    _result = OE_OK;

done:
    if (_buffer)
        free(_buffer);

    /* No `_ptrs` to free for deep copy. */

    return _result;
}

oe_result_t ecall_test_crls(
    oe_enclave_t* enclave,
    const char* root,
    const char* intermediate,
    const char* leaf1,
    const char* leaf2,
    const char* root_crl1,
    size_t root_crl1_size,
    const char* root_crl2,
    size_t root_crl2_size,
    const char* intermediate_crl1,
    size_t intermediate_crl1_size,
    const char* intermediate_crl2,
    size_t intermediate_crl2_size)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshalling struct. */
    ecall_test_crls_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Deep copy buffer. */
    /* No pointers to save for deep copy. */

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.root = (char*)root;
    _args.root_len = (root) ? (strlen(root) + 1) : 0;
    _args.intermediate = (char*)intermediate;
    _args.intermediate_len = (intermediate) ? (strlen(intermediate) + 1) : 0;
    _args.leaf1 = (char*)leaf1;
    _args.leaf1_len = (leaf1) ? (strlen(leaf1) + 1) : 0;
    _args.leaf2 = (char*)leaf2;
    _args.leaf2_len = (leaf2) ? (strlen(leaf2) + 1) : 0;
    _args.root_crl1 = (char*)root_crl1;
    _args.root_crl1_size = root_crl1_size;
    _args.root_crl2 = (char*)root_crl2;
    _args.root_crl2_size = root_crl2_size;
    _args.intermediate_crl1 = (char*)intermediate_crl1;
    _args.intermediate_crl1_size = intermediate_crl1_size;
    _args.intermediate_crl2 = (char*)intermediate_crl2;
    _args.intermediate_crl2_size = intermediate_crl2_size;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_test_crls_args_t));
    if (root)
        OE_ADD_SIZE(_input_buffer_size, _args.root_len * sizeof(char));
    if (intermediate)
        OE_ADD_SIZE(_input_buffer_size, _args.intermediate_len * sizeof(char));
    if (leaf1)
        OE_ADD_SIZE(_input_buffer_size, _args.leaf1_len * sizeof(char));
    if (leaf2)
        OE_ADD_SIZE(_input_buffer_size, _args.leaf2_len * sizeof(char));
    if (root_crl1)
        OE_ADD_SIZE(_input_buffer_size, _args.root_crl1_size);
    if (root_crl2)
        OE_ADD_SIZE(_input_buffer_size, _args.root_crl2_size);
    if (intermediate_crl1)
        OE_ADD_SIZE(_input_buffer_size, _args.intermediate_crl1_size);
    if (intermediate_crl2)
        OE_ADD_SIZE(_input_buffer_size, _args.intermediate_crl2_size);
    
    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_test_crls_args_t));
    /* There were no corresponding parameters. */
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (ecall_test_crls_args_t*)_input_buffer;
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    if (root)
        OE_WRITE_IN_PARAM(root, _args.root_len * sizeof(char), char*);
    if (intermediate)
        OE_WRITE_IN_PARAM(intermediate, _args.intermediate_len * sizeof(char), char*);
    if (leaf1)
        OE_WRITE_IN_PARAM(leaf1, _args.leaf1_len * sizeof(char), char*);
    if (leaf2)
        OE_WRITE_IN_PARAM(leaf2, _args.leaf2_len * sizeof(char), char*);
    if (root_crl1)
        OE_WRITE_IN_PARAM(root_crl1, _args.root_crl1_size, char*);
    if (root_crl2)
        OE_WRITE_IN_PARAM(root_crl2, _args.root_crl2_size, char*);
    if (intermediate_crl1)
        OE_WRITE_IN_PARAM(intermediate_crl1, _args.intermediate_crl1_size, char*);
    if (intermediate_crl2)
        OE_WRITE_IN_PARAM(intermediate_crl2, _args.intermediate_crl2_size, char*);
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function. */
    if ((_result = oe_call_enclave_function(
             enclave,
             crypto_crls_cert_chains_fcn_id_ecall_test_crls,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size,
             &_output_bytes_written)) != OE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (ecall_test_crls_args_t*)_output_buffer;
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Check if the call succeeded. */
    if ((_result = _pargs_out->_result) != OE_OK)
        goto done;
    
    /* Currently exactly _output_buffer_size bytes must be written. */
    if (_output_bytes_written != _output_buffer_size)
    {
        _result = OE_FAILURE;
        goto done;
    }
    
    /* Unmarshal return value and out, in-out parameters. */
    /* No return value. */
    /* No pointers to restore for deep copy. */
    /* There were no out nor in-out parameters. */

    _result = OE_OK;

done:
    if (_buffer)
        free(_buffer);

    /* No `_ptrs` to free for deep copy. */

    return _result;
}

/**** OCALL functions. ****/

/* There were no ocalls. */
/**** OCALL function table. ****/

static oe_ocall_func_t __crypto_crls_cert_chains_ocall_function_table[] = {
    
    NULL
};

oe_result_t oe_create_crypto_crls_cert_chains_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
#ifdef OE_CONTEXT_SWITCHLESS_EXPERIMENTAL_FEATURE
    const oe_enclave_config_t* configs,
    uint32_t config_count,
#else
    const void* config,
    uint32_t config_size,
#endif
    oe_enclave_t** enclave)
{
    return oe_create_enclave(
               path,
               type,
               flags,
#ifdef OE_CONTEXT_SWITCHLESS_EXPERIMENTAL_FEATURE
               configs,
               config_count,
#else
               config,
               config_size,
#endif
               __crypto_crls_cert_chains_ocall_function_table,
               0,
               enclave);
}

OE_EXTERNC_END
