/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_NO_TDATA_ARGS_H
#define EDGER8R_NO_TDATA_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _enc_set_value_args_t
{
    oe_result_t _result;
    uint64_t value;
} enc_set_value_args_t;

typedef struct _enc_get_value_args_t
{
    oe_result_t _result;
    uint64_t _retval;
} enc_get_value_args_t;

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** Trusted function IDs ****/
enum
{
    no_tdata_fcn_id_enc_set_value = 0,
    no_tdata_fcn_id_enc_get_value = 1,
    no_tdata_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{

    no_tdata_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_NO_TDATA_ARGS_H
