# CMake generated Testfile for 
# Source directory: C:/Users/brmclare/openenclave/tests/mbed
# Build directory: C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests/mbed/selftest "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_selftest")
add_test(tests/mbed/asn1write "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_asn1write")
add_test(tests/mbed/base64 "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_base64")
add_test(tests/mbed/ccm "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_ccm")
add_test(tests/mbed/cipher.aes "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_cipher.aes")
add_test(tests/mbed/cipher.ccm "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_cipher.ccm")
add_test(tests/mbed/cipher.des "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_cipher.des")
add_test(tests/mbed/cipher.gcm "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_cipher.gcm")
add_test(tests/mbed/cipher.padding "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_cipher.padding")
add_test(tests/mbed/cmac "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_cmac")
add_test(tests/mbed/ctr_drbg "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_ctr_drbg")
add_test(tests/mbed/des "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_des")
add_test(tests/mbed/ecdh "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_ecdh")
add_test(tests/mbed/ecdsa "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_ecdsa")
add_test(tests/mbed/ecp "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_ecp")
add_test(tests/mbed/entropy "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_entropy")
add_test(tests/mbed/error "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_error")
add_test(tests/mbed/gcm.aes128_en "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_gcm.aes128_en")
add_test(tests/mbed/gcm.aes192_en "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_gcm.aes192_en")
add_test(tests/mbed/gcm.aes256_en "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_gcm.aes256_en")
add_test(tests/mbed/gcm.aes128_de "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_gcm.aes128_de")
add_test(tests/mbed/gcm.aes192_de "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_gcm.aes192_de")
add_test(tests/mbed/gcm.aes256_de "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_gcm.aes256_de")
add_test(tests/mbed/hmac_drbg.misc "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_hmac_drbg.misc")
add_test(tests/mbed/hmac_drbg.no_reseed "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_hmac_drbg.no_reseed")
add_test(tests/mbed/hmac_drbg.nopr "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_hmac_drbg.nopr")
add_test(tests/mbed/hmac_drbg.pr "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_hmac_drbg.pr")
add_test(tests/mbed/md "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_md")
add_test(tests/mbed/mdx "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_mdx")
add_test(tests/mbed/mpi "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_mpi")
add_test(tests/mbed/pem "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_pem")
add_test(tests/mbed/pkcs1_v15 "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_pkcs1_v15")
add_test(tests/mbed/pkcs1_v21 "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_pkcs1_v21")
add_test(tests/mbed/pkcs5 "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_pkcs5")
add_test(tests/mbed/pk "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_pk")
add_test(tests/mbed/pkparse "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_pkparse")
add_test(tests/mbed/shax "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_shax")
add_test(tests/mbed/ssl "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_ssl")
add_test(tests/mbed/rsa "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_rsa")
add_test(tests/mbed/version "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_version")
add_test(tests/mbed/x509parse "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/host/libmbedtest_host.exe" "C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/enc/mbedtest_suite_x509parse")
subdirs("host")
subdirs("enc")
