/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ALL_ARGS_H
#define EDGER8R_ALL_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

#include <errno.h>

#include <openenclave/bits/result.h>

/**** User includes. ****/
#include "stdint.h"
#include "mytypes.h"

/**** User defined types in EDL. ****/
typedef enum type_enum_t
{
    TYPE_WCHAR_T,
    TYPE_LONG,
    TYPE_UNSIGNED_LONG,
    TYPE_LONG_DOUBLE
} type_enum_t;

typedef struct ShallowStruct
{
    uint64_t count;
    size_t size;
    uint64_t* ptr;
} ShallowStruct;

typedef struct CountStruct
{
    uint64_t count;
    size_t size;
    uint64_t* ptr;
} CountStruct;

typedef struct CountParamStruct
{
    uint64_t count;
    size_t size;
    uint64_t* ptr;
} CountParamStruct;

typedef struct SizeParamStruct
{
    uint64_t count;
    size_t size;
    uint64_t* ptr;
} SizeParamStruct;

typedef struct CountSizeParamStruct
{
    uint64_t count;
    size_t size;
    uint64_t* ptr;
} CountSizeParamStruct;

typedef struct NestedStruct
{
    int plain_int;
    int* array_of_int;
    ShallowStruct* shallow_struct;
    CountStruct* array_of_struct;
} NestedStruct;

typedef struct SuperNestedStruct
{
    NestedStruct* more_structs;
} SuperNestedStruct;

typedef struct IOVEC
{
    void* base;
    size_t len;
} IOVEC;

typedef enum Color
{
    Red = 1,
    Green = 2,
    Blue = 80000
} Color;

typedef struct MyStruct0
{
    int x;
} MyStruct0;

typedef struct MyStruct1
{
    MyStruct0 s0;
    int y;
} MyStruct1;

/**** ECALL marshalling structs. ****/
typedef struct _configure_args_t
{
    oe_result_t _result;
    uint8_t* enabled;
} configure_args_t;

typedef struct _aliasing_a_args_t
{
    oe_result_t _result;
    int _retval;
    char* d;
    size_t c;
} aliasing_a_args_t;

typedef struct _aliasing_b_args_t
{
    oe_result_t _result;
    int _retval;
    char** e;
    size_t* g;
    size_t f;
    char* h;
    size_t i;
    size_t* j;
} aliasing_b_args_t;

typedef struct _aliasing_c_args_t
{
    oe_result_t _result;
    int _retval;
    char* a;
} aliasing_c_args_t;

typedef struct _ecall_array_char_args_t
{
    oe_result_t _result;
    char* a1;
    char* a2;
    char* a3;
    char* a4;
} ecall_array_char_args_t;

typedef struct _ecall_array_wchar_t_args_t
{
    oe_result_t _result;
    wchar_t* a1;
    wchar_t* a2;
    wchar_t* a3;
    wchar_t* a4;
} ecall_array_wchar_t_args_t;

typedef struct _ecall_array_short_args_t
{
    oe_result_t _result;
    short int* a1;
    short int* a2;
    short int* a3;
    short int* a4;
} ecall_array_short_args_t;

typedef struct _ecall_array_int_args_t
{
    oe_result_t _result;
    int* a1;
    int* a2;
    int* a3;
    int* a4;
} ecall_array_int_args_t;

typedef struct _ecall_array_float_args_t
{
    oe_result_t _result;
    float* a1;
    float* a2;
    float* a3;
    float* a4;
} ecall_array_float_args_t;

typedef struct _ecall_array_double_args_t
{
    oe_result_t _result;
    double* a1;
    double* a2;
    double* a3;
    double* a4;
} ecall_array_double_args_t;

typedef struct _ecall_array_long_args_t
{
    oe_result_t _result;
    long int* a1;
    long int* a2;
    long int* a3;
    long int* a4;
} ecall_array_long_args_t;

typedef struct _ecall_array_size_t_args_t
{
    oe_result_t _result;
    size_t* a1;
    size_t* a2;
    size_t* a3;
    size_t* a4;
} ecall_array_size_t_args_t;

typedef struct _ecall_array_unsigned_args_t
{
    oe_result_t _result;
    unsigned int* a1;
    unsigned int* a2;
    unsigned int* a3;
    unsigned int* a4;
} ecall_array_unsigned_args_t;

typedef struct _ecall_array_int8_t_args_t
{
    oe_result_t _result;
    int8_t* a1;
    int8_t* a2;
    int8_t* a3;
    int8_t* a4;
} ecall_array_int8_t_args_t;

typedef struct _ecall_array_int16_t_args_t
{
    oe_result_t _result;
    int16_t* a1;
    int16_t* a2;
    int16_t* a3;
    int16_t* a4;
} ecall_array_int16_t_args_t;

typedef struct _ecall_array_int32_t_args_t
{
    oe_result_t _result;
    int32_t* a1;
    int32_t* a2;
    int32_t* a3;
    int32_t* a4;
} ecall_array_int32_t_args_t;

typedef struct _ecall_array_int64_t_args_t
{
    oe_result_t _result;
    int64_t* a1;
    int64_t* a2;
    int64_t* a3;
    int64_t* a4;
} ecall_array_int64_t_args_t;

typedef struct _ecall_array_uint8_t_args_t
{
    oe_result_t _result;
    uint8_t* a1;
    uint8_t* a2;
    uint8_t* a3;
    uint8_t* a4;
} ecall_array_uint8_t_args_t;

typedef struct _ecall_array_uint16_t_args_t
{
    oe_result_t _result;
    uint16_t* a1;
    uint16_t* a2;
    uint16_t* a3;
    uint16_t* a4;
} ecall_array_uint16_t_args_t;

typedef struct _ecall_array_uint32_t_args_t
{
    oe_result_t _result;
    uint32_t* a1;
    uint32_t* a2;
    uint32_t* a3;
    uint32_t* a4;
} ecall_array_uint32_t_args_t;

typedef struct _ecall_array_uint64_t_args_t
{
    oe_result_t _result;
    uint64_t* a1;
    uint64_t* a2;
    uint64_t* a3;
    uint64_t* a4;
} ecall_array_uint64_t_args_t;

typedef struct _ecall_array_long_long_args_t
{
    oe_result_t _result;
    long long* a1;
    long long* a2;
    long long* a3;
    long long* a4;
} ecall_array_long_long_args_t;

typedef struct _ecall_array_long_double_args_t
{
    oe_result_t _result;
    long double* a1;
    long double* a2;
    long double* a3;
    long double* a4;
} ecall_array_long_double_args_t;

typedef struct _ecall_array_unsigned_char_args_t
{
    oe_result_t _result;
    unsigned char* a1;
    unsigned char* a2;
    unsigned char* a3;
    unsigned char* a4;
} ecall_array_unsigned_char_args_t;

typedef struct _ecall_array_unsigned_short_args_t
{
    oe_result_t _result;
    unsigned short int* a1;
    unsigned short int* a2;
    unsigned short int* a3;
    unsigned short int* a4;
} ecall_array_unsigned_short_args_t;

typedef struct _ecall_array_unsigned_int_args_t
{
    oe_result_t _result;
    unsigned int* a1;
    unsigned int* a2;
    unsigned int* a3;
    unsigned int* a4;
} ecall_array_unsigned_int_args_t;

typedef struct _ecall_array_unsigned_long_args_t
{
    oe_result_t _result;
    unsigned long int* a1;
    unsigned long int* a2;
    unsigned long int* a3;
    unsigned long int* a4;
} ecall_array_unsigned_long_args_t;

typedef struct _ecall_array_unsigned_long_long_args_t
{
    oe_result_t _result;
    unsigned long long* a1;
    unsigned long long* a2;
    unsigned long long* a3;
    unsigned long long* a4;
} ecall_array_unsigned_long_long_args_t;

typedef struct _test_array_edl_ocalls_args_t
{
    oe_result_t _result;
} test_array_edl_ocalls_args_t;

typedef struct _ecall_array_assert_all_called_args_t
{
    oe_result_t _result;
} ecall_array_assert_all_called_args_t;

typedef struct _ecall_basic_types_args_t
{
    oe_result_t _result;
    char arg1;
    short int arg2;
    int arg3;
    float arg4;
    double arg5;
    size_t arg6;
    unsigned int arg7;
    int8_t arg8;
    int16_t arg9;
    int32_t arg10;
    int64_t arg11;
    uint8_t arg12;
    uint16_t arg13;
    uint32_t arg14;
    uint64_t arg15;
    long long arg16;
    unsigned char arg17;
    unsigned short int arg18;
    unsigned int arg19;
    unsigned long long arg20;
} ecall_basic_types_args_t;

typedef struct _ecall_basic_non_portable_types_args_t
{
    oe_result_t _result;
    wchar_t arg1;
    long int arg2;
    unsigned long int arg3;
    long double arg4;
} ecall_basic_non_portable_types_args_t;

typedef struct _get_enclave_sizeof_args_t
{
    oe_result_t _result;
    uint64_t _retval;
    type_enum_t t;
} get_enclave_sizeof_args_t;

typedef struct _ecall_ret_char_args_t
{
    oe_result_t _result;
    char _retval;
} ecall_ret_char_args_t;

typedef struct _ecall_ret_wchar_t_args_t
{
    oe_result_t _result;
    wchar_t _retval;
} ecall_ret_wchar_t_args_t;

typedef struct _ecall_ret_short_args_t
{
    oe_result_t _result;
    short int _retval;
} ecall_ret_short_args_t;

typedef struct _ecall_ret_int_args_t
{
    oe_result_t _result;
    int _retval;
} ecall_ret_int_args_t;

typedef struct _ecall_ret_float_args_t
{
    oe_result_t _result;
    float _retval;
} ecall_ret_float_args_t;

typedef struct _ecall_ret_double_args_t
{
    oe_result_t _result;
    double _retval;
} ecall_ret_double_args_t;

typedef struct _ecall_ret_long_args_t
{
    oe_result_t _result;
    long int _retval;
} ecall_ret_long_args_t;

typedef struct _ecall_ret_size_t_args_t
{
    oe_result_t _result;
    size_t _retval;
} ecall_ret_size_t_args_t;

typedef struct _ecall_ret_unsigned_args_t
{
    oe_result_t _result;
    unsigned int _retval;
} ecall_ret_unsigned_args_t;

typedef struct _ecall_ret_int8_t_args_t
{
    oe_result_t _result;
    int8_t _retval;
} ecall_ret_int8_t_args_t;

typedef struct _ecall_ret_int16_t_args_t
{
    oe_result_t _result;
    int16_t _retval;
} ecall_ret_int16_t_args_t;

typedef struct _ecall_ret_int32_t_args_t
{
    oe_result_t _result;
    int32_t _retval;
} ecall_ret_int32_t_args_t;

typedef struct _ecall_ret_int64_t_args_t
{
    oe_result_t _result;
    int64_t _retval;
} ecall_ret_int64_t_args_t;

typedef struct _ecall_ret_uint8_t_args_t
{
    oe_result_t _result;
    uint8_t _retval;
} ecall_ret_uint8_t_args_t;

typedef struct _ecall_ret_uint16_t_args_t
{
    oe_result_t _result;
    uint16_t _retval;
} ecall_ret_uint16_t_args_t;

typedef struct _ecall_ret_uint32_t_args_t
{
    oe_result_t _result;
    uint32_t _retval;
} ecall_ret_uint32_t_args_t;

typedef struct _ecall_ret_uint64_t_args_t
{
    oe_result_t _result;
    uint64_t _retval;
} ecall_ret_uint64_t_args_t;

typedef struct _ecall_ret_long_long_args_t
{
    oe_result_t _result;
    long long _retval;
} ecall_ret_long_long_args_t;

typedef struct _ecall_ret_unsigned_char_args_t
{
    oe_result_t _result;
    unsigned char _retval;
} ecall_ret_unsigned_char_args_t;

typedef struct _ecall_ret_unsigned_short_args_t
{
    oe_result_t _result;
    unsigned short int _retval;
} ecall_ret_unsigned_short_args_t;

typedef struct _ecall_ret_unsigned_int_args_t
{
    oe_result_t _result;
    unsigned int _retval;
} ecall_ret_unsigned_int_args_t;

typedef struct _ecall_ret_unsigned_long_args_t
{
    oe_result_t _result;
    unsigned long int _retval;
} ecall_ret_unsigned_long_args_t;

typedef struct _ecall_ret_long_double_args_t
{
    oe_result_t _result;
    long double _retval;
} ecall_ret_long_double_args_t;

typedef struct _ecall_ret_unsigned_long_long_args_t
{
    oe_result_t _result;
    unsigned long long _retval;
} ecall_ret_unsigned_long_long_args_t;

typedef struct _ecall_ret_void_args_t
{
    oe_result_t _result;
} ecall_ret_void_args_t;

typedef struct _test_basic_edl_ocalls_args_t
{
    oe_result_t _result;
} test_basic_edl_ocalls_args_t;

typedef struct _deepcopy_value_args_t
{
    oe_result_t _result;
    ShallowStruct s;
    uint64_t* ptr;
} deepcopy_value_args_t;

typedef struct _deepcopy_shallow_args_t
{
    oe_result_t _result;
    ShallowStruct* s;
    uint64_t* ptr;
} deepcopy_shallow_args_t;

typedef struct _deepcopy_count_args_t
{
    oe_result_t _result;
    CountStruct* s;
} deepcopy_count_args_t;

typedef struct _deepcopy_countparam_args_t
{
    oe_result_t _result;
    CountParamStruct* s;
} deepcopy_countparam_args_t;

typedef struct _deepcopy_sizeparam_args_t
{
    oe_result_t _result;
    SizeParamStruct* s;
} deepcopy_sizeparam_args_t;

typedef struct _deepcopy_countsizeparam_args_t
{
    oe_result_t _result;
    CountSizeParamStruct* s;
} deepcopy_countsizeparam_args_t;

typedef struct _deepcopy_countsizeparam_size_args_t
{
    oe_result_t _result;
    CountSizeParamStruct* s;
} deepcopy_countsizeparam_size_args_t;

typedef struct _deepcopy_countsizeparam_count_args_t
{
    oe_result_t _result;
    CountSizeParamStruct* s;
} deepcopy_countsizeparam_count_args_t;

typedef struct _deepcopy_countparamarray_args_t
{
    oe_result_t _result;
    CountParamStruct* s;
} deepcopy_countparamarray_args_t;

typedef struct _deepcopy_sizeparamarray_args_t
{
    oe_result_t _result;
    SizeParamStruct* s;
} deepcopy_sizeparamarray_args_t;

typedef struct _deepcopy_countsizeparamarray_args_t
{
    oe_result_t _result;
    CountSizeParamStruct* s;
} deepcopy_countsizeparamarray_args_t;

typedef struct _deepcopy_nested_args_t
{
    oe_result_t _result;
    NestedStruct* n;
} deepcopy_nested_args_t;

typedef struct _deepcopy_super_nested_args_t
{
    oe_result_t _result;
    SuperNestedStruct* s;
    size_t n;
} deepcopy_super_nested_args_t;

typedef struct _deepcopy_null_args_t
{
    oe_result_t _result;
    CountStruct* s;
} deepcopy_null_args_t;

typedef struct _deepcopy_out_count_args_t
{
    oe_result_t _result;
    CountStruct* s;
} deepcopy_out_count_args_t;

typedef struct _deepcopy_iovec_args_t
{
    oe_result_t _result;
    IOVEC* iov;
    size_t n;
} deepcopy_iovec_args_t;

typedef struct _ecall_enum1_args_t
{
    oe_result_t _result;
    Color _retval;
    Color a1;
    Color* a2;
    Color* a3;
    Color* a4;
    Color* a5;
    Color* a6;
    Color* a7;
    Color* a8;
    Color* a9;
    Color* a10;
    Color* a11;
    Color* a12;
    Color* a13;
    Color* a14;
    Color* a15;
    Color* a16;
    Color* a17;
    Color* a18;
    Color* a19;
    size_t count;
    size_t size;
} ecall_enum1_args_t;

typedef struct _test_enum_edl_ocalls_args_t
{
    oe_result_t _result;
} test_enum_edl_ocalls_args_t;

typedef struct _test_errno_edl_ocalls_args_t
{
    oe_result_t _result;
} test_errno_edl_ocalls_args_t;

typedef struct _ecall_foreign_ptr_1_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
} ecall_foreign_ptr_1_args_t;

typedef struct _ecall_foreign_ptr_2_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
} ecall_foreign_ptr_2_args_t;

typedef struct _ecall_foreign_ptr_3_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
} ecall_foreign_ptr_3_args_t;

typedef struct _ecall_foreign_ptr_4_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
    size_t count;
} ecall_foreign_ptr_4_args_t;

typedef struct _ecall_foreign_ptr_5_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
    size_t size;
} ecall_foreign_ptr_5_args_t;

typedef struct _ecall_foreign_isptr_1_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
} ecall_foreign_isptr_1_args_t;

typedef struct _ecall_foreign_isptr_2_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
} ecall_foreign_isptr_2_args_t;

typedef struct _ecall_foreign_isptr_3_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
} ecall_foreign_isptr_3_args_t;

typedef struct _ecall_foreign_isptr_4_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
    size_t count;
} ecall_foreign_isptr_4_args_t;

typedef struct _ecall_foreign_isptr_5_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
    size_t size;
} ecall_foreign_isptr_5_args_t;

typedef struct _ecall_foreign_isary_args_t
{
    oe_result_t _result;
    /* foreign array of type my_type3 */ void* a1;
    /* foreign array of type my_type3 */ void* a2;
    /* foreign array of type my_type3 */ void* a3;
} ecall_foreign_isary_args_t;

typedef struct _ecall_foreign_value_args_t
{
    oe_result_t _result;
    my_type1 _retval;
    my_type1 a1;
} ecall_foreign_value_args_t;

typedef struct _test_foreign_edl_ocalls_args_t
{
    oe_result_t _result;
} test_foreign_edl_ocalls_args_t;

typedef struct _ecall_pointer_char_args_t
{
    oe_result_t _result;
    char* _retval;
    char* p1;
    char* p2;
    char* p3;
    char* p4;
    char* p5;
    char* p6;
    char* p7;
    char* p8;
    char* p9;
    char* p10;
    char* p11;
    char* p12;
    char* p13;
    char* p14;
    char* p15;
    char* p16;
    int pcount;
    int psize;
} ecall_pointer_char_args_t;

typedef struct _ecall_pointer_wchar_t_args_t
{
    oe_result_t _result;
    wchar_t* _retval;
    wchar_t* p1;
    wchar_t* p2;
    wchar_t* p3;
    wchar_t* p4;
    wchar_t* p5;
    wchar_t* p6;
    wchar_t* p7;
    wchar_t* p8;
    wchar_t* p9;
    wchar_t* p10;
    wchar_t* p11;
    wchar_t* p12;
    wchar_t* p13;
    wchar_t* p14;
    wchar_t* p15;
    wchar_t* p16;
    int pcount;
    int psize;
} ecall_pointer_wchar_t_args_t;

typedef struct _ecall_pointer_short_args_t
{
    oe_result_t _result;
    short int* _retval;
    short int* p1;
    short int* p2;
    short int* p3;
    short int* p4;
    short int* p5;
    short int* p6;
    short int* p7;
    short int* p8;
    short int* p9;
    short int* p10;
    short int* p11;
    short int* p12;
    short int* p13;
    short int* p14;
    short int* p15;
    short int* p16;
    int pcount;
    int psize;
} ecall_pointer_short_args_t;

typedef struct _ecall_pointer_int_args_t
{
    oe_result_t _result;
    int* _retval;
    int* p1;
    int* p2;
    int* p3;
    int* p4;
    int* p5;
    int* p6;
    int* p7;
    int* p8;
    int* p9;
    int* p10;
    int* p11;
    int* p12;
    int* p13;
    int* p14;
    int* p15;
    int* p16;
    int pcount;
    int psize;
} ecall_pointer_int_args_t;

typedef struct _ecall_pointer_float_args_t
{
    oe_result_t _result;
    float* _retval;
    float* p1;
    float* p2;
    float* p3;
    float* p4;
    float* p5;
    float* p6;
    float* p7;
    float* p8;
    float* p9;
    float* p10;
    float* p11;
    float* p12;
    float* p13;
    float* p14;
    float* p15;
    float* p16;
    int pcount;
    int psize;
} ecall_pointer_float_args_t;

typedef struct _ecall_pointer_double_args_t
{
    oe_result_t _result;
    double* _retval;
    double* p1;
    double* p2;
    double* p3;
    double* p4;
    double* p5;
    double* p6;
    double* p7;
    double* p8;
    double* p9;
    double* p10;
    double* p11;
    double* p12;
    double* p13;
    double* p14;
    double* p15;
    double* p16;
    int pcount;
    int psize;
} ecall_pointer_double_args_t;

typedef struct _ecall_pointer_long_args_t
{
    oe_result_t _result;
    long int* _retval;
    long int* p1;
    long int* p2;
    long int* p3;
    long int* p4;
    long int* p5;
    long int* p6;
    long int* p7;
    long int* p8;
    long int* p9;
    long int* p10;
    long int* p11;
    long int* p12;
    long int* p13;
    long int* p14;
    long int* p15;
    long int* p16;
    int pcount;
    int psize;
} ecall_pointer_long_args_t;

typedef struct _ecall_pointer_size_t_args_t
{
    oe_result_t _result;
    size_t* _retval;
    size_t* p1;
    size_t* p2;
    size_t* p3;
    size_t* p4;
    size_t* p5;
    size_t* p6;
    size_t* p7;
    size_t* p8;
    size_t* p9;
    size_t* p10;
    size_t* p11;
    size_t* p12;
    size_t* p13;
    size_t* p14;
    size_t* p15;
    size_t* p16;
    int pcount;
    int psize;
} ecall_pointer_size_t_args_t;

typedef struct _ecall_pointer_unsigned_args_t
{
    oe_result_t _result;
    unsigned int* _retval;
    unsigned int* p1;
    unsigned int* p2;
    unsigned int* p3;
    unsigned int* p4;
    unsigned int* p5;
    unsigned int* p6;
    unsigned int* p7;
    unsigned int* p8;
    unsigned int* p9;
    unsigned int* p10;
    unsigned int* p11;
    unsigned int* p12;
    unsigned int* p13;
    unsigned int* p14;
    unsigned int* p15;
    unsigned int* p16;
    int pcount;
    int psize;
} ecall_pointer_unsigned_args_t;

typedef struct _ecall_pointer_int8_t_args_t
{
    oe_result_t _result;
    int8_t* _retval;
    int8_t* p1;
    int8_t* p2;
    int8_t* p3;
    int8_t* p4;
    int8_t* p5;
    int8_t* p6;
    int8_t* p7;
    int8_t* p8;
    int8_t* p9;
    int8_t* p10;
    int8_t* p11;
    int8_t* p12;
    int8_t* p13;
    int8_t* p14;
    int8_t* p15;
    int8_t* p16;
    int pcount;
    int psize;
} ecall_pointer_int8_t_args_t;

typedef struct _ecall_pointer_int16_t_args_t
{
    oe_result_t _result;
    int16_t* _retval;
    int16_t* p1;
    int16_t* p2;
    int16_t* p3;
    int16_t* p4;
    int16_t* p5;
    int16_t* p6;
    int16_t* p7;
    int16_t* p8;
    int16_t* p9;
    int16_t* p10;
    int16_t* p11;
    int16_t* p12;
    int16_t* p13;
    int16_t* p14;
    int16_t* p15;
    int16_t* p16;
    int pcount;
    int psize;
} ecall_pointer_int16_t_args_t;

typedef struct _ecall_pointer_int32_t_args_t
{
    oe_result_t _result;
    int32_t* _retval;
    int32_t* p1;
    int32_t* p2;
    int32_t* p3;
    int32_t* p4;
    int32_t* p5;
    int32_t* p6;
    int32_t* p7;
    int32_t* p8;
    int32_t* p9;
    int32_t* p10;
    int32_t* p11;
    int32_t* p12;
    int32_t* p13;
    int32_t* p14;
    int32_t* p15;
    int32_t* p16;
    int pcount;
    int psize;
} ecall_pointer_int32_t_args_t;

typedef struct _ecall_pointer_int64_t_args_t
{
    oe_result_t _result;
    int64_t* _retval;
    int64_t* p1;
    int64_t* p2;
    int64_t* p3;
    int64_t* p4;
    int64_t* p5;
    int64_t* p6;
    int64_t* p7;
    int64_t* p8;
    int64_t* p9;
    int64_t* p10;
    int64_t* p11;
    int64_t* p12;
    int64_t* p13;
    int64_t* p14;
    int64_t* p15;
    int64_t* p16;
    int pcount;
    int psize;
} ecall_pointer_int64_t_args_t;

typedef struct _ecall_pointer_uint8_t_args_t
{
    oe_result_t _result;
    uint8_t* _retval;
    uint8_t* p1;
    uint8_t* p2;
    uint8_t* p3;
    uint8_t* p4;
    uint8_t* p5;
    uint8_t* p6;
    uint8_t* p7;
    uint8_t* p8;
    uint8_t* p9;
    uint8_t* p10;
    uint8_t* p11;
    uint8_t* p12;
    uint8_t* p13;
    uint8_t* p14;
    uint8_t* p15;
    uint8_t* p16;
    int pcount;
    int psize;
} ecall_pointer_uint8_t_args_t;

typedef struct _ecall_pointer_uint16_t_args_t
{
    oe_result_t _result;
    uint16_t* _retval;
    uint16_t* p1;
    uint16_t* p2;
    uint16_t* p3;
    uint16_t* p4;
    uint16_t* p5;
    uint16_t* p6;
    uint16_t* p7;
    uint16_t* p8;
    uint16_t* p9;
    uint16_t* p10;
    uint16_t* p11;
    uint16_t* p12;
    uint16_t* p13;
    uint16_t* p14;
    uint16_t* p15;
    uint16_t* p16;
    int pcount;
    int psize;
} ecall_pointer_uint16_t_args_t;

typedef struct _ecall_pointer_uint32_t_args_t
{
    oe_result_t _result;
    uint32_t* _retval;
    uint32_t* p1;
    uint32_t* p2;
    uint32_t* p3;
    uint32_t* p4;
    uint32_t* p5;
    uint32_t* p6;
    uint32_t* p7;
    uint32_t* p8;
    uint32_t* p9;
    uint32_t* p10;
    uint32_t* p11;
    uint32_t* p12;
    uint32_t* p13;
    uint32_t* p14;
    uint32_t* p15;
    uint32_t* p16;
    int pcount;
    int psize;
} ecall_pointer_uint32_t_args_t;

typedef struct _ecall_pointer_uint64_t_args_t
{
    oe_result_t _result;
    uint64_t* _retval;
    uint64_t* p1;
    uint64_t* p2;
    uint64_t* p3;
    uint64_t* p4;
    uint64_t* p5;
    uint64_t* p6;
    uint64_t* p7;
    uint64_t* p8;
    uint64_t* p9;
    uint64_t* p10;
    uint64_t* p11;
    uint64_t* p12;
    uint64_t* p13;
    uint64_t* p14;
    uint64_t* p15;
    uint64_t* p16;
    int pcount;
    int psize;
} ecall_pointer_uint64_t_args_t;

typedef struct _ecall_pointer_long_long_args_t
{
    oe_result_t _result;
    long long* _retval;
    long long* p1;
    long long* p2;
    long long* p3;
    long long* p4;
    long long* p5;
    long long* p6;
    long long* p7;
    long long* p8;
    long long* p9;
    long long* p10;
    long long* p11;
    long long* p12;
    long long* p13;
    long long* p14;
    long long* p15;
    long long* p16;
    int pcount;
    int psize;
} ecall_pointer_long_long_args_t;

typedef struct _ecall_pointer_unsigned_char_args_t
{
    oe_result_t _result;
    unsigned char* _retval;
    unsigned char* p1;
    unsigned char* p2;
    unsigned char* p3;
    unsigned char* p4;
    unsigned char* p5;
    unsigned char* p6;
    unsigned char* p7;
    unsigned char* p8;
    unsigned char* p9;
    unsigned char* p10;
    unsigned char* p11;
    unsigned char* p12;
    unsigned char* p13;
    unsigned char* p14;
    unsigned char* p15;
    unsigned char* p16;
    int pcount;
    int psize;
} ecall_pointer_unsigned_char_args_t;

typedef struct _ecall_pointer_unsigned_short_args_t
{
    oe_result_t _result;
    unsigned short int* _retval;
    unsigned short int* p1;
    unsigned short int* p2;
    unsigned short int* p3;
    unsigned short int* p4;
    unsigned short int* p5;
    unsigned short int* p6;
    unsigned short int* p7;
    unsigned short int* p8;
    unsigned short int* p9;
    unsigned short int* p10;
    unsigned short int* p11;
    unsigned short int* p12;
    unsigned short int* p13;
    unsigned short int* p14;
    unsigned short int* p15;
    unsigned short int* p16;
    int pcount;
    int psize;
} ecall_pointer_unsigned_short_args_t;

typedef struct _ecall_pointer_unsigned_int_args_t
{
    oe_result_t _result;
    unsigned int* _retval;
    unsigned int* p1;
    unsigned int* p2;
    unsigned int* p3;
    unsigned int* p4;
    unsigned int* p5;
    unsigned int* p6;
    unsigned int* p7;
    unsigned int* p8;
    unsigned int* p9;
    unsigned int* p10;
    unsigned int* p11;
    unsigned int* p12;
    unsigned int* p13;
    unsigned int* p14;
    unsigned int* p15;
    unsigned int* p16;
    int pcount;
    int psize;
} ecall_pointer_unsigned_int_args_t;

typedef struct _ecall_pointer_unsigned_long_args_t
{
    oe_result_t _result;
    unsigned long int* _retval;
    unsigned long int* p1;
    unsigned long int* p2;
    unsigned long int* p3;
    unsigned long int* p4;
    unsigned long int* p5;
    unsigned long int* p6;
    unsigned long int* p7;
    unsigned long int* p8;
    unsigned long int* p9;
    unsigned long int* p10;
    unsigned long int* p11;
    unsigned long int* p12;
    unsigned long int* p13;
    unsigned long int* p14;
    unsigned long int* p15;
    unsigned long int* p16;
    int pcount;
    int psize;
} ecall_pointer_unsigned_long_args_t;

typedef struct _ecall_pointer_unsigned_long_long_args_t
{
    oe_result_t _result;
    unsigned long long* _retval;
    unsigned long long* p1;
    unsigned long long* p2;
    unsigned long long* p3;
    unsigned long long* p4;
    unsigned long long* p5;
    unsigned long long* p6;
    unsigned long long* p7;
    unsigned long long* p8;
    unsigned long long* p9;
    unsigned long long* p10;
    unsigned long long* p11;
    unsigned long long* p12;
    unsigned long long* p13;
    unsigned long long* p14;
    unsigned long long* p15;
    unsigned long long* p16;
    int pcount;
    int psize;
} ecall_pointer_unsigned_long_long_args_t;

typedef struct _ecall_pointer_long_double_args_t
{
    oe_result_t _result;
    long double* _retval;
    long double* p1;
    long double* p2;
    long double* p3;
    long double* p4;
    long double* p5;
    long double* p6;
    long double* p7;
    long double* p8;
    long double* p9;
    long double* p10;
    long double* p11;
    long double* p12;
    long double* p13;
    long double* p14;
    long double* p15;
    long double* p16;
    int pcount;
    int psize;
} ecall_pointer_long_double_args_t;

typedef struct _ecall_count_attribute_all_types_args_t
{
    oe_result_t _result;
    int* b1;
    int* b2;
    int* b3;
    int* b4;
    int* b5;
    int* b6;
    int* b7;
    int* b8;
    int* b9;
    int* b10;
    int* b11;
    int* b12;
    int* b13;
    int* b14;
    int* b15;
    int* b16;
    int* b17;
    int* b18;
    int* b19;
    int* b20;
    int* b21;
    int* b22;
    int* b23;
    int* b24;
    char char_count;
    short int short_count;
    int int_count;
    float float_count;
    double double_count;
    long int long_count;
    size_t size_t_count;
    unsigned int unsigned_count;
    int8_t int8_t_count;
    int16_t int16_t_count;
    int32_t int32_t_count;
    int64_t int64_t_count;
    uint8_t uint8_t_count;
    uint16_t uint16_t_count;
    uint32_t uint32_t_count;
    uint64_t uint64_t_count;
    wchar_t wchar_t_count;
    long long long_long_count;
    long double long_double_count;
    unsigned char unsigned_char_count;
    unsigned short int unsigned_short_count;
    unsigned int unsigned_int_count;
    unsigned long int unsigned_long_count;
    unsigned long long unsigned_long_long_count;
} ecall_count_attribute_all_types_args_t;

typedef struct _ecall_size_attribute_all_types_args_t
{
    oe_result_t _result;
    int* b1;
    int* b2;
    int* b3;
    int* b4;
    int* b5;
    int* b6;
    int* b7;
    int* b8;
    int* b9;
    int* b10;
    int* b11;
    int* b12;
    int* b13;
    int* b14;
    int* b15;
    int* b16;
    int* b17;
    int* b18;
    int* b19;
    int* b20;
    int* b21;
    int* b22;
    int* b23;
    int* b24;
    char char_size;
    short int short_size;
    int int_size;
    float float_size;
    double double_size;
    long int long_size;
    size_t size_t_size;
    unsigned int unsigned_size;
    int8_t int8_t_size;
    int16_t int16_t_size;
    int32_t int32_t_size;
    int64_t int64_t_size;
    uint8_t uint8_t_size;
    uint16_t uint16_t_size;
    uint32_t uint32_t_size;
    uint64_t uint64_t_size;
    wchar_t wchar_t_size;
    long long long_long_size;
    long double long_double_size;
    unsigned char unsigned_char_size;
    unsigned short int unsigned_short_size;
    unsigned int unsigned_int_size;
    unsigned long int unsigned_long_size;
    unsigned long long unsigned_long_long_size;
} ecall_size_attribute_all_types_args_t;

typedef struct _test_pointer_edl_ocalls_args_t
{
    oe_result_t _result;
} test_pointer_edl_ocalls_args_t;

typedef struct _ecall_pointer_assert_all_called_args_t
{
    oe_result_t _result;
} ecall_pointer_assert_all_called_args_t;

typedef struct _ecall_string_fun1_args_t
{
    oe_result_t _result;
    char* s;
    size_t s_len;
} ecall_string_fun1_args_t;

typedef struct _ecall_string_fun2_args_t
{
    oe_result_t _result;
    char* s;
    size_t s_len;
} ecall_string_fun2_args_t;

typedef struct _ecall_string_fun3_args_t
{
    oe_result_t _result;
    char* s;
    size_t s_len;
} ecall_string_fun3_args_t;

typedef struct _ecall_string_fun5_args_t
{
    oe_result_t _result;
    char* s;
} ecall_string_fun5_args_t;

typedef struct _ecall_string_fun6_args_t
{
    oe_result_t _result;
    char* s;
} ecall_string_fun6_args_t;

typedef struct _ecall_string_fun7_args_t
{
    oe_result_t _result;
    char* s1;
    size_t s1_len;
    char* s2;
    size_t s2_len;
} ecall_string_fun7_args_t;

typedef struct _test_string_edl_ocalls_args_t
{
    oe_result_t _result;
} test_string_edl_ocalls_args_t;

typedef struct _ecall_wstring_fun1_args_t
{
    oe_result_t _result;
    wchar_t* s;
    size_t s_len;
} ecall_wstring_fun1_args_t;

typedef struct _ecall_wstring_fun2_args_t
{
    oe_result_t _result;
    wchar_t* s;
    size_t s_len;
} ecall_wstring_fun2_args_t;

typedef struct _ecall_wstring_fun3_args_t
{
    oe_result_t _result;
    wchar_t* s;
    size_t s_len;
} ecall_wstring_fun3_args_t;

typedef struct _ecall_wstring_fun5_args_t
{
    oe_result_t _result;
    wchar_t* s;
} ecall_wstring_fun5_args_t;

typedef struct _ecall_wstring_fun6_args_t
{
    oe_result_t _result;
    wchar_t* s;
} ecall_wstring_fun6_args_t;

typedef struct _ecall_wstring_fun7_args_t
{
    oe_result_t _result;
    wchar_t* s1;
    size_t s1_len;
    wchar_t* s2;
    size_t s2_len;
} ecall_wstring_fun7_args_t;

typedef struct _test_wstring_edl_ocalls_args_t
{
    oe_result_t _result;
} test_wstring_edl_ocalls_args_t;

typedef struct _ecall_string_no_null_terminator_args_t
{
    oe_result_t _result;
    char* s1;
    size_t s1_len;
    char* s2;
    size_t s2_len;
} ecall_string_no_null_terminator_args_t;

typedef struct _ecall_wstring_no_null_terminator_args_t
{
    oe_result_t _result;
    wchar_t* s1;
    size_t s1_len;
    wchar_t* s2;
    size_t s2_len;
} ecall_wstring_no_null_terminator_args_t;

typedef struct _ecall_struct1_args_t
{
    oe_result_t _result;
    MyStruct1 _retval;
    MyStruct1 a1;
    MyStruct1* a2;
    MyStruct1* a3;
    MyStruct1* a4;
    MyStruct1* a5;
    MyStruct1* a6;
    MyStruct1* a7;
    MyStruct1* a8;
    MyStruct1* a9;
    MyStruct1* a10;
    MyStruct1* a11;
    MyStruct1* a12;
    MyStruct1* a13;
    MyStruct1* a14;
    MyStruct1* a15;
    MyStruct1* a16;
    MyStruct1* a17;
    MyStruct1* a18;
    MyStruct1* a19;
    size_t count;
    size_t size;
} ecall_struct1_args_t;

typedef struct _test_struct_edl_ocalls_args_t
{
    oe_result_t _result;
} test_struct_edl_ocalls_args_t;

typedef struct _ecall_sum_args_t
{
    oe_result_t _result;
    int _retval;
    int a;
    int b;
} ecall_sum_args_t;

typedef struct _switchless_ecall_sum_args_t
{
    oe_result_t _result;
    int _retval;
    int a;
    int b;
} switchless_ecall_sum_args_t;

typedef struct _test_switchless_edl_ocalls_args_t
{
    oe_result_t _result;
} test_switchless_edl_ocalls_args_t;

typedef struct _enc_foo1_args_t
{
    oe_result_t _result;
} enc_foo1_args_t;

/**** OCALL marshalling structs. ****/
typedef struct _ocall_array_char_args_t
{
    oe_result_t _result;
    char* a1;
    char* a2;
    char* a3;
    char* a4;
} ocall_array_char_args_t;

typedef struct _ocall_array_wchar_t_args_t
{
    oe_result_t _result;
    wchar_t* a1;
    wchar_t* a2;
    wchar_t* a3;
    wchar_t* a4;
} ocall_array_wchar_t_args_t;

typedef struct _ocall_array_short_args_t
{
    oe_result_t _result;
    short int* a1;
    short int* a2;
    short int* a3;
    short int* a4;
} ocall_array_short_args_t;

typedef struct _ocall_array_int_args_t
{
    oe_result_t _result;
    int* a1;
    int* a2;
    int* a3;
    int* a4;
} ocall_array_int_args_t;

typedef struct _ocall_array_float_args_t
{
    oe_result_t _result;
    float* a1;
    float* a2;
    float* a3;
    float* a4;
} ocall_array_float_args_t;

typedef struct _ocall_array_double_args_t
{
    oe_result_t _result;
    double* a1;
    double* a2;
    double* a3;
    double* a4;
} ocall_array_double_args_t;

typedef struct _ocall_array_long_args_t
{
    oe_result_t _result;
    long int* a1;
    long int* a2;
    long int* a3;
    long int* a4;
} ocall_array_long_args_t;

typedef struct _ocall_array_size_t_args_t
{
    oe_result_t _result;
    size_t* a1;
    size_t* a2;
    size_t* a3;
    size_t* a4;
} ocall_array_size_t_args_t;

typedef struct _ocall_array_unsigned_args_t
{
    oe_result_t _result;
    unsigned int* a1;
    unsigned int* a2;
    unsigned int* a3;
    unsigned int* a4;
} ocall_array_unsigned_args_t;

typedef struct _ocall_array_int8_t_args_t
{
    oe_result_t _result;
    int8_t* a1;
    int8_t* a2;
    int8_t* a3;
    int8_t* a4;
} ocall_array_int8_t_args_t;

typedef struct _ocall_array_int16_t_args_t
{
    oe_result_t _result;
    int16_t* a1;
    int16_t* a2;
    int16_t* a3;
    int16_t* a4;
} ocall_array_int16_t_args_t;

typedef struct _ocall_array_int32_t_args_t
{
    oe_result_t _result;
    int32_t* a1;
    int32_t* a2;
    int32_t* a3;
    int32_t* a4;
} ocall_array_int32_t_args_t;

typedef struct _ocall_array_int64_t_args_t
{
    oe_result_t _result;
    int64_t* a1;
    int64_t* a2;
    int64_t* a3;
    int64_t* a4;
} ocall_array_int64_t_args_t;

typedef struct _ocall_array_uint8_t_args_t
{
    oe_result_t _result;
    uint8_t* a1;
    uint8_t* a2;
    uint8_t* a3;
    uint8_t* a4;
} ocall_array_uint8_t_args_t;

typedef struct _ocall_array_uint16_t_args_t
{
    oe_result_t _result;
    uint16_t* a1;
    uint16_t* a2;
    uint16_t* a3;
    uint16_t* a4;
} ocall_array_uint16_t_args_t;

typedef struct _ocall_array_uint32_t_args_t
{
    oe_result_t _result;
    uint32_t* a1;
    uint32_t* a2;
    uint32_t* a3;
    uint32_t* a4;
} ocall_array_uint32_t_args_t;

typedef struct _ocall_array_uint64_t_args_t
{
    oe_result_t _result;
    uint64_t* a1;
    uint64_t* a2;
    uint64_t* a3;
    uint64_t* a4;
} ocall_array_uint64_t_args_t;

typedef struct _ocall_array_long_long_args_t
{
    oe_result_t _result;
    long long* a1;
    long long* a2;
    long long* a3;
    long long* a4;
} ocall_array_long_long_args_t;

typedef struct _ocall_array_unsigned_char_args_t
{
    oe_result_t _result;
    unsigned char* a1;
    unsigned char* a2;
    unsigned char* a3;
    unsigned char* a4;
} ocall_array_unsigned_char_args_t;

typedef struct _ocall_array_unsigned_short_args_t
{
    oe_result_t _result;
    unsigned short int* a1;
    unsigned short int* a2;
    unsigned short int* a3;
    unsigned short int* a4;
} ocall_array_unsigned_short_args_t;

typedef struct _ocall_array_unsigned_int_args_t
{
    oe_result_t _result;
    unsigned int* a1;
    unsigned int* a2;
    unsigned int* a3;
    unsigned int* a4;
} ocall_array_unsigned_int_args_t;

typedef struct _ocall_array_unsigned_long_args_t
{
    oe_result_t _result;
    unsigned long int* a1;
    unsigned long int* a2;
    unsigned long int* a3;
    unsigned long int* a4;
} ocall_array_unsigned_long_args_t;

typedef struct _ocall_array_unsigned_long_long_args_t
{
    oe_result_t _result;
    unsigned long long* a1;
    unsigned long long* a2;
    unsigned long long* a3;
    unsigned long long* a4;
} ocall_array_unsigned_long_long_args_t;

typedef struct _ocall_array_long_double_args_t
{
    oe_result_t _result;
    long double* a1;
    long double* a2;
    long double* a3;
    long double* a4;
} ocall_array_long_double_args_t;

typedef struct _ocall_array_assert_all_called_args_t
{
    oe_result_t _result;
} ocall_array_assert_all_called_args_t;

typedef struct _ocall_basic_types_args_t
{
    oe_result_t _result;
    char arg1;
    short int arg2;
    int arg3;
    float arg4;
    double arg5;
    size_t arg6;
    unsigned int arg7;
    int8_t arg8;
    int16_t arg9;
    int32_t arg10;
    int64_t arg11;
    uint8_t arg12;
    uint16_t arg13;
    uint32_t arg14;
    uint64_t arg15;
    long long arg16;
    unsigned char arg17;
    unsigned short int arg18;
    unsigned int arg19;
    unsigned long long arg20;
} ocall_basic_types_args_t;

typedef struct _ocall_basic_non_portable_types_args_t
{
    oe_result_t _result;
    wchar_t arg1;
    long int arg2;
    unsigned long int arg3;
    long double arg4;
} ocall_basic_non_portable_types_args_t;

typedef struct _get_host_sizeof_args_t
{
    oe_result_t _result;
    uint64_t _retval;
    type_enum_t t;
} get_host_sizeof_args_t;

typedef struct _ocall_ret_char_args_t
{
    oe_result_t _result;
    char _retval;
} ocall_ret_char_args_t;

typedef struct _ocall_ret_wchar_t_args_t
{
    oe_result_t _result;
    wchar_t _retval;
} ocall_ret_wchar_t_args_t;

typedef struct _ocall_ret_short_args_t
{
    oe_result_t _result;
    short int _retval;
} ocall_ret_short_args_t;

typedef struct _ocall_ret_int_args_t
{
    oe_result_t _result;
    int _retval;
} ocall_ret_int_args_t;

typedef struct _ocall_ret_float_args_t
{
    oe_result_t _result;
    float _retval;
} ocall_ret_float_args_t;

typedef struct _ocall_ret_double_args_t
{
    oe_result_t _result;
    double _retval;
} ocall_ret_double_args_t;

typedef struct _ocall_ret_long_args_t
{
    oe_result_t _result;
    long int _retval;
} ocall_ret_long_args_t;

typedef struct _ocall_ret_size_t_args_t
{
    oe_result_t _result;
    size_t _retval;
} ocall_ret_size_t_args_t;

typedef struct _ocall_ret_unsigned_args_t
{
    oe_result_t _result;
    unsigned int _retval;
} ocall_ret_unsigned_args_t;

typedef struct _ocall_ret_int8_t_args_t
{
    oe_result_t _result;
    int8_t _retval;
} ocall_ret_int8_t_args_t;

typedef struct _ocall_ret_int16_t_args_t
{
    oe_result_t _result;
    int16_t _retval;
} ocall_ret_int16_t_args_t;

typedef struct _ocall_ret_int32_t_args_t
{
    oe_result_t _result;
    int32_t _retval;
} ocall_ret_int32_t_args_t;

typedef struct _ocall_ret_int64_t_args_t
{
    oe_result_t _result;
    int64_t _retval;
} ocall_ret_int64_t_args_t;

typedef struct _ocall_ret_uint8_t_args_t
{
    oe_result_t _result;
    uint8_t _retval;
} ocall_ret_uint8_t_args_t;

typedef struct _ocall_ret_uint16_t_args_t
{
    oe_result_t _result;
    uint16_t _retval;
} ocall_ret_uint16_t_args_t;

typedef struct _ocall_ret_uint32_t_args_t
{
    oe_result_t _result;
    uint32_t _retval;
} ocall_ret_uint32_t_args_t;

typedef struct _ocall_ret_uint64_t_args_t
{
    oe_result_t _result;
    uint64_t _retval;
} ocall_ret_uint64_t_args_t;

typedef struct _ocall_ret_long_long_args_t
{
    oe_result_t _result;
    long long _retval;
} ocall_ret_long_long_args_t;

typedef struct _ocall_ret_unsigned_char_args_t
{
    oe_result_t _result;
    unsigned char _retval;
} ocall_ret_unsigned_char_args_t;

typedef struct _ocall_ret_unsigned_short_args_t
{
    oe_result_t _result;
    unsigned short int _retval;
} ocall_ret_unsigned_short_args_t;

typedef struct _ocall_ret_unsigned_int_args_t
{
    oe_result_t _result;
    unsigned int _retval;
} ocall_ret_unsigned_int_args_t;

typedef struct _ocall_ret_unsigned_long_args_t
{
    oe_result_t _result;
    unsigned long int _retval;
} ocall_ret_unsigned_long_args_t;

typedef struct _ocall_ret_long_double_args_t
{
    oe_result_t _result;
    long double _retval;
} ocall_ret_long_double_args_t;

typedef struct _ocall_ret_unsigned_long_long_args_t
{
    oe_result_t _result;
    unsigned long long _retval;
} ocall_ret_unsigned_long_long_args_t;

typedef struct _ocall_ret_void_args_t
{
    oe_result_t _result;
} ocall_ret_void_args_t;

typedef struct _ocall_enum1_args_t
{
    oe_result_t _result;
    Color _retval;
    Color a1;
    Color* a2;
    Color* a3;
    Color* a4;
    Color* a5;
    Color* a6;
    Color* a7;
    Color* a8;
    Color* a9;
    Color* a10;
    Color* a11;
    Color* a12;
    Color* a13;
    Color* a14;
    Color* a15;
    Color* a16;
    Color* a17;
    Color* a18;
    Color* a19;
    size_t count;
    size_t size;
} ocall_enum1_args_t;

typedef struct _ocall_errno_args_t
{
    oe_result_t _result;
    int _ocall_errno;
} ocall_errno_args_t;

typedef struct _ocall_set_host_errno_args_t
{
    oe_result_t _result;
    int e;
} ocall_set_host_errno_args_t;

typedef struct _ocall_noop_args_t
{
    oe_result_t _result;
    int _ocall_errno;
} ocall_noop_args_t;

typedef struct _ocall_foreign_ptr_1_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
} ocall_foreign_ptr_1_args_t;

typedef struct _ocall_foreign_ptr_2_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
} ocall_foreign_ptr_2_args_t;

typedef struct _ocall_foreign_ptr_3_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
} ocall_foreign_ptr_3_args_t;

typedef struct _ocall_foreign_ptr_4_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
    size_t count;
} ocall_foreign_ptr_4_args_t;

typedef struct _ocall_foreign_ptr_5_args_t
{
    oe_result_t _result;
    my_type1* a1;
    my_type1* a2;
    my_type1* a3;
    size_t size;
} ocall_foreign_ptr_5_args_t;

typedef struct _ocall_foreign_isptr_1_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
} ocall_foreign_isptr_1_args_t;

typedef struct _ocall_foreign_isptr_2_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
} ocall_foreign_isptr_2_args_t;

typedef struct _ocall_foreign_isptr_3_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
} ocall_foreign_isptr_3_args_t;

typedef struct _ocall_foreign_isptr_4_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
    size_t count;
} ocall_foreign_isptr_4_args_t;

typedef struct _ocall_foreign_isptr_5_args_t
{
    oe_result_t _result;
    my_type2 a1;
    my_type2 a2;
    my_type2 a3;
    size_t size;
} ocall_foreign_isptr_5_args_t;

typedef struct _ocall_foreign_isary_args_t
{
    oe_result_t _result;
    /* foreign array of type my_type3 */ void* a1;
    /* foreign array of type my_type3 */ void* a2;
    /* foreign array of type my_type3 */ void* a3;
} ocall_foreign_isary_args_t;

typedef struct _ocall_foreign_value_args_t
{
    oe_result_t _result;
    my_type1 _retval;
    my_type1 a1;
} ocall_foreign_value_args_t;

typedef struct _ocall_pointer_char_args_t
{
    oe_result_t _result;
    char* _retval;
    char* p1;
    char* p2;
    char* p3;
    char* p4;
    char* p5;
    char* p6;
    char* p7;
    char* p8;
    char* p9;
    char* p10;
    char* p11;
    char* p12;
    char* p13;
    char* p14;
    char* p15;
    char* p16;
    int pcount;
    int psize;
} ocall_pointer_char_args_t;

typedef struct _ocall_pointer_wchar_t_args_t
{
    oe_result_t _result;
    wchar_t* _retval;
    wchar_t* p1;
    wchar_t* p2;
    wchar_t* p3;
    wchar_t* p4;
    wchar_t* p5;
    wchar_t* p6;
    wchar_t* p7;
    wchar_t* p8;
    wchar_t* p9;
    wchar_t* p10;
    wchar_t* p11;
    wchar_t* p12;
    wchar_t* p13;
    wchar_t* p14;
    wchar_t* p15;
    wchar_t* p16;
    int pcount;
    int psize;
} ocall_pointer_wchar_t_args_t;

typedef struct _ocall_pointer_short_args_t
{
    oe_result_t _result;
    short int* _retval;
    short int* p1;
    short int* p2;
    short int* p3;
    short int* p4;
    short int* p5;
    short int* p6;
    short int* p7;
    short int* p8;
    short int* p9;
    short int* p10;
    short int* p11;
    short int* p12;
    short int* p13;
    short int* p14;
    short int* p15;
    short int* p16;
    int pcount;
    int psize;
} ocall_pointer_short_args_t;

typedef struct _ocall_pointer_int_args_t
{
    oe_result_t _result;
    int* _retval;
    int* p1;
    int* p2;
    int* p3;
    int* p4;
    int* p5;
    int* p6;
    int* p7;
    int* p8;
    int* p9;
    int* p10;
    int* p11;
    int* p12;
    int* p13;
    int* p14;
    int* p15;
    int* p16;
    int pcount;
    int psize;
} ocall_pointer_int_args_t;

typedef struct _ocall_pointer_float_args_t
{
    oe_result_t _result;
    float* _retval;
    float* p1;
    float* p2;
    float* p3;
    float* p4;
    float* p5;
    float* p6;
    float* p7;
    float* p8;
    float* p9;
    float* p10;
    float* p11;
    float* p12;
    float* p13;
    float* p14;
    float* p15;
    float* p16;
    int pcount;
    int psize;
} ocall_pointer_float_args_t;

typedef struct _ocall_pointer_double_args_t
{
    oe_result_t _result;
    double* _retval;
    double* p1;
    double* p2;
    double* p3;
    double* p4;
    double* p5;
    double* p6;
    double* p7;
    double* p8;
    double* p9;
    double* p10;
    double* p11;
    double* p12;
    double* p13;
    double* p14;
    double* p15;
    double* p16;
    int pcount;
    int psize;
} ocall_pointer_double_args_t;

typedef struct _ocall_pointer_long_args_t
{
    oe_result_t _result;
    long int* _retval;
    long int* p1;
    long int* p2;
    long int* p3;
    long int* p4;
    long int* p5;
    long int* p6;
    long int* p7;
    long int* p8;
    long int* p9;
    long int* p10;
    long int* p11;
    long int* p12;
    long int* p13;
    long int* p14;
    long int* p15;
    long int* p16;
    int pcount;
    int psize;
} ocall_pointer_long_args_t;

typedef struct _ocall_pointer_size_t_args_t
{
    oe_result_t _result;
    size_t* _retval;
    size_t* p1;
    size_t* p2;
    size_t* p3;
    size_t* p4;
    size_t* p5;
    size_t* p6;
    size_t* p7;
    size_t* p8;
    size_t* p9;
    size_t* p10;
    size_t* p11;
    size_t* p12;
    size_t* p13;
    size_t* p14;
    size_t* p15;
    size_t* p16;
    int pcount;
    int psize;
} ocall_pointer_size_t_args_t;

typedef struct _ocall_pointer_unsigned_args_t
{
    oe_result_t _result;
    unsigned int* _retval;
    unsigned int* p1;
    unsigned int* p2;
    unsigned int* p3;
    unsigned int* p4;
    unsigned int* p5;
    unsigned int* p6;
    unsigned int* p7;
    unsigned int* p8;
    unsigned int* p9;
    unsigned int* p10;
    unsigned int* p11;
    unsigned int* p12;
    unsigned int* p13;
    unsigned int* p14;
    unsigned int* p15;
    unsigned int* p16;
    int pcount;
    int psize;
} ocall_pointer_unsigned_args_t;

typedef struct _ocall_pointer_int8_t_args_t
{
    oe_result_t _result;
    int8_t* _retval;
    int8_t* p1;
    int8_t* p2;
    int8_t* p3;
    int8_t* p4;
    int8_t* p5;
    int8_t* p6;
    int8_t* p7;
    int8_t* p8;
    int8_t* p9;
    int8_t* p10;
    int8_t* p11;
    int8_t* p12;
    int8_t* p13;
    int8_t* p14;
    int8_t* p15;
    int8_t* p16;
    int pcount;
    int psize;
} ocall_pointer_int8_t_args_t;

typedef struct _ocall_pointer_int16_t_args_t
{
    oe_result_t _result;
    int16_t* _retval;
    int16_t* p1;
    int16_t* p2;
    int16_t* p3;
    int16_t* p4;
    int16_t* p5;
    int16_t* p6;
    int16_t* p7;
    int16_t* p8;
    int16_t* p9;
    int16_t* p10;
    int16_t* p11;
    int16_t* p12;
    int16_t* p13;
    int16_t* p14;
    int16_t* p15;
    int16_t* p16;
    int pcount;
    int psize;
} ocall_pointer_int16_t_args_t;

typedef struct _ocall_pointer_int32_t_args_t
{
    oe_result_t _result;
    int32_t* _retval;
    int32_t* p1;
    int32_t* p2;
    int32_t* p3;
    int32_t* p4;
    int32_t* p5;
    int32_t* p6;
    int32_t* p7;
    int32_t* p8;
    int32_t* p9;
    int32_t* p10;
    int32_t* p11;
    int32_t* p12;
    int32_t* p13;
    int32_t* p14;
    int32_t* p15;
    int32_t* p16;
    int pcount;
    int psize;
} ocall_pointer_int32_t_args_t;

typedef struct _ocall_pointer_int64_t_args_t
{
    oe_result_t _result;
    int64_t* _retval;
    int64_t* p1;
    int64_t* p2;
    int64_t* p3;
    int64_t* p4;
    int64_t* p5;
    int64_t* p6;
    int64_t* p7;
    int64_t* p8;
    int64_t* p9;
    int64_t* p10;
    int64_t* p11;
    int64_t* p12;
    int64_t* p13;
    int64_t* p14;
    int64_t* p15;
    int64_t* p16;
    int pcount;
    int psize;
} ocall_pointer_int64_t_args_t;

typedef struct _ocall_pointer_uint8_t_args_t
{
    oe_result_t _result;
    uint8_t* _retval;
    uint8_t* p1;
    uint8_t* p2;
    uint8_t* p3;
    uint8_t* p4;
    uint8_t* p5;
    uint8_t* p6;
    uint8_t* p7;
    uint8_t* p8;
    uint8_t* p9;
    uint8_t* p10;
    uint8_t* p11;
    uint8_t* p12;
    uint8_t* p13;
    uint8_t* p14;
    uint8_t* p15;
    uint8_t* p16;
    int pcount;
    int psize;
} ocall_pointer_uint8_t_args_t;

typedef struct _ocall_pointer_uint16_t_args_t
{
    oe_result_t _result;
    uint16_t* _retval;
    uint16_t* p1;
    uint16_t* p2;
    uint16_t* p3;
    uint16_t* p4;
    uint16_t* p5;
    uint16_t* p6;
    uint16_t* p7;
    uint16_t* p8;
    uint16_t* p9;
    uint16_t* p10;
    uint16_t* p11;
    uint16_t* p12;
    uint16_t* p13;
    uint16_t* p14;
    uint16_t* p15;
    uint16_t* p16;
    int pcount;
    int psize;
} ocall_pointer_uint16_t_args_t;

typedef struct _ocall_pointer_uint32_t_args_t
{
    oe_result_t _result;
    uint32_t* _retval;
    uint32_t* p1;
    uint32_t* p2;
    uint32_t* p3;
    uint32_t* p4;
    uint32_t* p5;
    uint32_t* p6;
    uint32_t* p7;
    uint32_t* p8;
    uint32_t* p9;
    uint32_t* p10;
    uint32_t* p11;
    uint32_t* p12;
    uint32_t* p13;
    uint32_t* p14;
    uint32_t* p15;
    uint32_t* p16;
    int pcount;
    int psize;
} ocall_pointer_uint32_t_args_t;

typedef struct _ocall_pointer_uint64_t_args_t
{
    oe_result_t _result;
    uint64_t* _retval;
    uint64_t* p1;
    uint64_t* p2;
    uint64_t* p3;
    uint64_t* p4;
    uint64_t* p5;
    uint64_t* p6;
    uint64_t* p7;
    uint64_t* p8;
    uint64_t* p9;
    uint64_t* p10;
    uint64_t* p11;
    uint64_t* p12;
    uint64_t* p13;
    uint64_t* p14;
    uint64_t* p15;
    uint64_t* p16;
    int pcount;
    int psize;
} ocall_pointer_uint64_t_args_t;

typedef struct _ocall_pointer_long_long_args_t
{
    oe_result_t _result;
    long long* _retval;
    long long* p1;
    long long* p2;
    long long* p3;
    long long* p4;
    long long* p5;
    long long* p6;
    long long* p7;
    long long* p8;
    long long* p9;
    long long* p10;
    long long* p11;
    long long* p12;
    long long* p13;
    long long* p14;
    long long* p15;
    long long* p16;
    int pcount;
    int psize;
} ocall_pointer_long_long_args_t;

typedef struct _ocall_pointer_unsigned_char_args_t
{
    oe_result_t _result;
    unsigned char* _retval;
    unsigned char* p1;
    unsigned char* p2;
    unsigned char* p3;
    unsigned char* p4;
    unsigned char* p5;
    unsigned char* p6;
    unsigned char* p7;
    unsigned char* p8;
    unsigned char* p9;
    unsigned char* p10;
    unsigned char* p11;
    unsigned char* p12;
    unsigned char* p13;
    unsigned char* p14;
    unsigned char* p15;
    unsigned char* p16;
    int pcount;
    int psize;
} ocall_pointer_unsigned_char_args_t;

typedef struct _ocall_pointer_unsigned_short_args_t
{
    oe_result_t _result;
    unsigned short int* _retval;
    unsigned short int* p1;
    unsigned short int* p2;
    unsigned short int* p3;
    unsigned short int* p4;
    unsigned short int* p5;
    unsigned short int* p6;
    unsigned short int* p7;
    unsigned short int* p8;
    unsigned short int* p9;
    unsigned short int* p10;
    unsigned short int* p11;
    unsigned short int* p12;
    unsigned short int* p13;
    unsigned short int* p14;
    unsigned short int* p15;
    unsigned short int* p16;
    int pcount;
    int psize;
} ocall_pointer_unsigned_short_args_t;

typedef struct _ocall_pointer_unsigned_int_args_t
{
    oe_result_t _result;
    unsigned int* _retval;
    unsigned int* p1;
    unsigned int* p2;
    unsigned int* p3;
    unsigned int* p4;
    unsigned int* p5;
    unsigned int* p6;
    unsigned int* p7;
    unsigned int* p8;
    unsigned int* p9;
    unsigned int* p10;
    unsigned int* p11;
    unsigned int* p12;
    unsigned int* p13;
    unsigned int* p14;
    unsigned int* p15;
    unsigned int* p16;
    int pcount;
    int psize;
} ocall_pointer_unsigned_int_args_t;

typedef struct _ocall_pointer_unsigned_long_args_t
{
    oe_result_t _result;
    unsigned long int* _retval;
    unsigned long int* p1;
    unsigned long int* p2;
    unsigned long int* p3;
    unsigned long int* p4;
    unsigned long int* p5;
    unsigned long int* p6;
    unsigned long int* p7;
    unsigned long int* p8;
    unsigned long int* p9;
    unsigned long int* p10;
    unsigned long int* p11;
    unsigned long int* p12;
    unsigned long int* p13;
    unsigned long int* p14;
    unsigned long int* p15;
    unsigned long int* p16;
    int pcount;
    int psize;
} ocall_pointer_unsigned_long_args_t;

typedef struct _ocall_pointer_unsigned_long_long_args_t
{
    oe_result_t _result;
    unsigned long long* _retval;
    unsigned long long* p1;
    unsigned long long* p2;
    unsigned long long* p3;
    unsigned long long* p4;
    unsigned long long* p5;
    unsigned long long* p6;
    unsigned long long* p7;
    unsigned long long* p8;
    unsigned long long* p9;
    unsigned long long* p10;
    unsigned long long* p11;
    unsigned long long* p12;
    unsigned long long* p13;
    unsigned long long* p14;
    unsigned long long* p15;
    unsigned long long* p16;
    int pcount;
    int psize;
} ocall_pointer_unsigned_long_long_args_t;

typedef struct _ocall_pointer_long_double_args_t
{
    oe_result_t _result;
    long double* _retval;
    long double* p1;
    long double* p2;
    long double* p3;
    long double* p4;
    long double* p5;
    long double* p6;
    long double* p7;
    long double* p8;
    long double* p9;
    long double* p10;
    long double* p11;
    long double* p12;
    long double* p13;
    long double* p14;
    long double* p15;
    long double* p16;
    int pcount;
    int psize;
} ocall_pointer_long_double_args_t;

typedef struct _ocall_count_attribute_all_types_args_t
{
    oe_result_t _result;
    int* b1;
    int* b2;
    int* b3;
    int* b4;
    int* b5;
    int* b6;
    int* b7;
    int* b8;
    int* b9;
    int* b10;
    int* b11;
    int* b12;
    int* b13;
    int* b14;
    int* b15;
    int* b16;
    int* b17;
    int* b18;
    int* b19;
    int* b20;
    int* b21;
    int* b22;
    int* b23;
    int* b24;
    char char_count;
    short int short_count;
    int int_count;
    float float_count;
    double double_count;
    long int long_count;
    size_t size_t_count;
    unsigned int unsigned_count;
    int8_t int8_t_count;
    int16_t int16_t_count;
    int32_t int32_t_count;
    int64_t int64_t_count;
    uint8_t uint8_t_count;
    uint16_t uint16_t_count;
    uint32_t uint32_t_count;
    uint64_t uint64_t_count;
    wchar_t wchar_t_count;
    long long long_long_count;
    long double long_double_count;
    unsigned char unsigned_char_count;
    unsigned short int unsigned_short_count;
    unsigned int unsigned_int_count;
    unsigned long int unsigned_long_count;
    unsigned long long unsigned_long_long_count;
} ocall_count_attribute_all_types_args_t;

typedef struct _ocall_size_attribute_all_types_args_t
{
    oe_result_t _result;
    int* b1;
    int* b2;
    int* b3;
    int* b4;
    int* b5;
    int* b6;
    int* b7;
    int* b8;
    int* b9;
    int* b10;
    int* b11;
    int* b12;
    int* b13;
    int* b14;
    int* b15;
    int* b16;
    int* b17;
    int* b18;
    int* b19;
    int* b20;
    int* b21;
    int* b22;
    int* b23;
    int* b24;
    char char_size;
    short int short_size;
    int int_size;
    float float_size;
    double double_size;
    long int long_size;
    size_t size_t_size;
    unsigned int unsigned_size;
    int8_t int8_t_size;
    int16_t int16_t_size;
    int32_t int32_t_size;
    int64_t int64_t_size;
    uint8_t uint8_t_size;
    uint16_t uint16_t_size;
    uint32_t uint32_t_size;
    uint64_t uint64_t_size;
    wchar_t wchar_t_size;
    long long long_long_size;
    long double long_double_size;
    unsigned char unsigned_char_size;
    unsigned short int unsigned_short_size;
    unsigned int unsigned_int_size;
    unsigned long int unsigned_long_size;
    unsigned long long unsigned_long_long_size;
} ocall_size_attribute_all_types_args_t;

typedef struct _ocall_pointer_assert_all_called_args_t
{
    oe_result_t _result;
} ocall_pointer_assert_all_called_args_t;

typedef struct _ocall_string_fun1_args_t
{
    oe_result_t _result;
    char* s;
    size_t s_len;
} ocall_string_fun1_args_t;

typedef struct _ocall_string_fun2_args_t
{
    oe_result_t _result;
    char* s;
    size_t s_len;
} ocall_string_fun2_args_t;

typedef struct _ocall_string_fun3_args_t
{
    oe_result_t _result;
    char* s;
    size_t s_len;
} ocall_string_fun3_args_t;

typedef struct _ocall_string_fun5_args_t
{
    oe_result_t _result;
    char* s;
} ocall_string_fun5_args_t;

typedef struct _ocall_string_fun6_args_t
{
    oe_result_t _result;
    char* s;
} ocall_string_fun6_args_t;

typedef struct _ocall_string_fun7_args_t
{
    oe_result_t _result;
    char* s1;
    size_t s1_len;
    char* s2;
    size_t s2_len;
} ocall_string_fun7_args_t;

typedef struct _ocall_wstring_fun1_args_t
{
    oe_result_t _result;
    wchar_t* s;
    size_t s_len;
} ocall_wstring_fun1_args_t;

typedef struct _ocall_wstring_fun2_args_t
{
    oe_result_t _result;
    wchar_t* s;
    size_t s_len;
} ocall_wstring_fun2_args_t;

typedef struct _ocall_wstring_fun3_args_t
{
    oe_result_t _result;
    wchar_t* s;
    size_t s_len;
} ocall_wstring_fun3_args_t;

typedef struct _ocall_wstring_fun5_args_t
{
    oe_result_t _result;
    wchar_t* s;
} ocall_wstring_fun5_args_t;

typedef struct _ocall_wstring_fun6_args_t
{
    oe_result_t _result;
    wchar_t* s;
} ocall_wstring_fun6_args_t;

typedef struct _ocall_wstring_fun7_args_t
{
    oe_result_t _result;
    wchar_t* s1;
    size_t s1_len;
    wchar_t* s2;
    size_t s2_len;
} ocall_wstring_fun7_args_t;

typedef struct _ocall_string_no_null_terminator_args_t
{
    oe_result_t _result;
    bool erasenull;
    char* s;
    size_t s_len;
} ocall_string_no_null_terminator_args_t;

typedef struct _ocall_wstring_no_null_terminator_args_t
{
    oe_result_t _result;
    bool erasenull;
    wchar_t* s;
    size_t s_len;
} ocall_wstring_no_null_terminator_args_t;

typedef struct _ocall_struct1_args_t
{
    oe_result_t _result;
    MyStruct1 _retval;
    MyStruct1 a1;
    MyStruct1* a2;
    MyStruct1* a3;
    MyStruct1* a4;
    MyStruct1* a5;
    MyStruct1* a6;
    MyStruct1* a7;
    MyStruct1* a8;
    MyStruct1* a9;
    MyStruct1* a10;
    MyStruct1* a11;
    MyStruct1* a12;
    MyStruct1* a13;
    MyStruct1* a14;
    MyStruct1* a15;
    MyStruct1* a16;
    MyStruct1* a17;
    MyStruct1* a18;
    MyStruct1* a19;
    size_t count;
    size_t size;
} ocall_struct1_args_t;

typedef struct _ocall_sum_args_t
{
    oe_result_t _result;
    int _retval;
    int a;
    int b;
} ocall_sum_args_t;

typedef struct _switchless_ocall_sum_args_t
{
    oe_result_t _result;
    int _retval;
    int a;
    int b;
} switchless_ocall_sum_args_t;

typedef struct _host_foo1_args_t
{
    oe_result_t _result;
} host_foo1_args_t;

/**** Trusted function IDs ****/
enum
{
    all_fcn_id_configure = 0,
    all_fcn_id_aliasing_a = 1,
    all_fcn_id_aliasing_b = 2,
    all_fcn_id_aliasing_c = 3,
    all_fcn_id_ecall_array_char = 4,
    all_fcn_id_ecall_array_wchar_t = 5,
    all_fcn_id_ecall_array_short = 6,
    all_fcn_id_ecall_array_int = 7,
    all_fcn_id_ecall_array_float = 8,
    all_fcn_id_ecall_array_double = 9,
    all_fcn_id_ecall_array_long = 10,
    all_fcn_id_ecall_array_size_t = 11,
    all_fcn_id_ecall_array_unsigned = 12,
    all_fcn_id_ecall_array_int8_t = 13,
    all_fcn_id_ecall_array_int16_t = 14,
    all_fcn_id_ecall_array_int32_t = 15,
    all_fcn_id_ecall_array_int64_t = 16,
    all_fcn_id_ecall_array_uint8_t = 17,
    all_fcn_id_ecall_array_uint16_t = 18,
    all_fcn_id_ecall_array_uint32_t = 19,
    all_fcn_id_ecall_array_uint64_t = 20,
    all_fcn_id_ecall_array_long_long = 21,
    all_fcn_id_ecall_array_long_double = 22,
    all_fcn_id_ecall_array_unsigned_char = 23,
    all_fcn_id_ecall_array_unsigned_short = 24,
    all_fcn_id_ecall_array_unsigned_int = 25,
    all_fcn_id_ecall_array_unsigned_long = 26,
    all_fcn_id_ecall_array_unsigned_long_long = 27,
    all_fcn_id_test_array_edl_ocalls = 28,
    all_fcn_id_ecall_array_assert_all_called = 29,
    all_fcn_id_ecall_basic_types = 30,
    all_fcn_id_ecall_basic_non_portable_types = 31,
    all_fcn_id_get_enclave_sizeof = 32,
    all_fcn_id_ecall_ret_char = 33,
    all_fcn_id_ecall_ret_wchar_t = 34,
    all_fcn_id_ecall_ret_short = 35,
    all_fcn_id_ecall_ret_int = 36,
    all_fcn_id_ecall_ret_float = 37,
    all_fcn_id_ecall_ret_double = 38,
    all_fcn_id_ecall_ret_long = 39,
    all_fcn_id_ecall_ret_size_t = 40,
    all_fcn_id_ecall_ret_unsigned = 41,
    all_fcn_id_ecall_ret_int8_t = 42,
    all_fcn_id_ecall_ret_int16_t = 43,
    all_fcn_id_ecall_ret_int32_t = 44,
    all_fcn_id_ecall_ret_int64_t = 45,
    all_fcn_id_ecall_ret_uint8_t = 46,
    all_fcn_id_ecall_ret_uint16_t = 47,
    all_fcn_id_ecall_ret_uint32_t = 48,
    all_fcn_id_ecall_ret_uint64_t = 49,
    all_fcn_id_ecall_ret_long_long = 50,
    all_fcn_id_ecall_ret_unsigned_char = 51,
    all_fcn_id_ecall_ret_unsigned_short = 52,
    all_fcn_id_ecall_ret_unsigned_int = 53,
    all_fcn_id_ecall_ret_unsigned_long = 54,
    all_fcn_id_ecall_ret_long_double = 55,
    all_fcn_id_ecall_ret_unsigned_long_long = 56,
    all_fcn_id_ecall_ret_void = 57,
    all_fcn_id_test_basic_edl_ocalls = 58,
    all_fcn_id_deepcopy_value = 59,
    all_fcn_id_deepcopy_shallow = 60,
    all_fcn_id_deepcopy_count = 61,
    all_fcn_id_deepcopy_countparam = 62,
    all_fcn_id_deepcopy_sizeparam = 63,
    all_fcn_id_deepcopy_countsizeparam = 64,
    all_fcn_id_deepcopy_countsizeparam_size = 65,
    all_fcn_id_deepcopy_countsizeparam_count = 66,
    all_fcn_id_deepcopy_countparamarray = 67,
    all_fcn_id_deepcopy_sizeparamarray = 68,
    all_fcn_id_deepcopy_countsizeparamarray = 69,
    all_fcn_id_deepcopy_nested = 70,
    all_fcn_id_deepcopy_super_nested = 71,
    all_fcn_id_deepcopy_null = 72,
    all_fcn_id_deepcopy_out_count = 73,
    all_fcn_id_deepcopy_iovec = 74,
    all_fcn_id_ecall_enum1 = 75,
    all_fcn_id_test_enum_edl_ocalls = 76,
    all_fcn_id_test_errno_edl_ocalls = 77,
    all_fcn_id_ecall_foreign_ptr_1 = 78,
    all_fcn_id_ecall_foreign_ptr_2 = 79,
    all_fcn_id_ecall_foreign_ptr_3 = 80,
    all_fcn_id_ecall_foreign_ptr_4 = 81,
    all_fcn_id_ecall_foreign_ptr_5 = 82,
    all_fcn_id_ecall_foreign_isptr_1 = 83,
    all_fcn_id_ecall_foreign_isptr_2 = 84,
    all_fcn_id_ecall_foreign_isptr_3 = 85,
    all_fcn_id_ecall_foreign_isptr_4 = 86,
    all_fcn_id_ecall_foreign_isptr_5 = 87,
    all_fcn_id_ecall_foreign_isary = 88,
    all_fcn_id_ecall_foreign_value = 89,
    all_fcn_id_test_foreign_edl_ocalls = 90,
    all_fcn_id_ecall_pointer_char = 91,
    all_fcn_id_ecall_pointer_wchar_t = 92,
    all_fcn_id_ecall_pointer_short = 93,
    all_fcn_id_ecall_pointer_int = 94,
    all_fcn_id_ecall_pointer_float = 95,
    all_fcn_id_ecall_pointer_double = 96,
    all_fcn_id_ecall_pointer_long = 97,
    all_fcn_id_ecall_pointer_size_t = 98,
    all_fcn_id_ecall_pointer_unsigned = 99,
    all_fcn_id_ecall_pointer_int8_t = 100,
    all_fcn_id_ecall_pointer_int16_t = 101,
    all_fcn_id_ecall_pointer_int32_t = 102,
    all_fcn_id_ecall_pointer_int64_t = 103,
    all_fcn_id_ecall_pointer_uint8_t = 104,
    all_fcn_id_ecall_pointer_uint16_t = 105,
    all_fcn_id_ecall_pointer_uint32_t = 106,
    all_fcn_id_ecall_pointer_uint64_t = 107,
    all_fcn_id_ecall_pointer_long_long = 108,
    all_fcn_id_ecall_pointer_unsigned_char = 109,
    all_fcn_id_ecall_pointer_unsigned_short = 110,
    all_fcn_id_ecall_pointer_unsigned_int = 111,
    all_fcn_id_ecall_pointer_unsigned_long = 112,
    all_fcn_id_ecall_pointer_unsigned_long_long = 113,
    all_fcn_id_ecall_pointer_long_double = 114,
    all_fcn_id_ecall_count_attribute_all_types = 115,
    all_fcn_id_ecall_size_attribute_all_types = 116,
    all_fcn_id_test_pointer_edl_ocalls = 117,
    all_fcn_id_ecall_pointer_assert_all_called = 118,
    all_fcn_id_ecall_string_fun1 = 119,
    all_fcn_id_ecall_string_fun2 = 120,
    all_fcn_id_ecall_string_fun3 = 121,
    all_fcn_id_ecall_string_fun5 = 122,
    all_fcn_id_ecall_string_fun6 = 123,
    all_fcn_id_ecall_string_fun7 = 124,
    all_fcn_id_test_string_edl_ocalls = 125,
    all_fcn_id_ecall_wstring_fun1 = 126,
    all_fcn_id_ecall_wstring_fun2 = 127,
    all_fcn_id_ecall_wstring_fun3 = 128,
    all_fcn_id_ecall_wstring_fun5 = 129,
    all_fcn_id_ecall_wstring_fun6 = 130,
    all_fcn_id_ecall_wstring_fun7 = 131,
    all_fcn_id_test_wstring_edl_ocalls = 132,
    all_fcn_id_ecall_string_no_null_terminator = 133,
    all_fcn_id_ecall_wstring_no_null_terminator = 134,
    all_fcn_id_ecall_struct1 = 135,
    all_fcn_id_test_struct_edl_ocalls = 136,
    all_fcn_id_ecall_sum = 137,
    all_fcn_id_switchless_ecall_sum = 138,
    all_fcn_id_test_switchless_edl_ocalls = 139,
    all_fcn_id_enc_foo1 = 140,
    all_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{
    all_fcn_id_ocall_array_char = 0,
    all_fcn_id_ocall_array_wchar_t = 1,
    all_fcn_id_ocall_array_short = 2,
    all_fcn_id_ocall_array_int = 3,
    all_fcn_id_ocall_array_float = 4,
    all_fcn_id_ocall_array_double = 5,
    all_fcn_id_ocall_array_long = 6,
    all_fcn_id_ocall_array_size_t = 7,
    all_fcn_id_ocall_array_unsigned = 8,
    all_fcn_id_ocall_array_int8_t = 9,
    all_fcn_id_ocall_array_int16_t = 10,
    all_fcn_id_ocall_array_int32_t = 11,
    all_fcn_id_ocall_array_int64_t = 12,
    all_fcn_id_ocall_array_uint8_t = 13,
    all_fcn_id_ocall_array_uint16_t = 14,
    all_fcn_id_ocall_array_uint32_t = 15,
    all_fcn_id_ocall_array_uint64_t = 16,
    all_fcn_id_ocall_array_long_long = 17,
    all_fcn_id_ocall_array_unsigned_char = 18,
    all_fcn_id_ocall_array_unsigned_short = 19,
    all_fcn_id_ocall_array_unsigned_int = 20,
    all_fcn_id_ocall_array_unsigned_long = 21,
    all_fcn_id_ocall_array_unsigned_long_long = 22,
    all_fcn_id_ocall_array_long_double = 23,
    all_fcn_id_ocall_array_assert_all_called = 24,
    all_fcn_id_ocall_basic_types = 25,
    all_fcn_id_ocall_basic_non_portable_types = 26,
    all_fcn_id_get_host_sizeof = 27,
    all_fcn_id_ocall_ret_char = 28,
    all_fcn_id_ocall_ret_wchar_t = 29,
    all_fcn_id_ocall_ret_short = 30,
    all_fcn_id_ocall_ret_int = 31,
    all_fcn_id_ocall_ret_float = 32,
    all_fcn_id_ocall_ret_double = 33,
    all_fcn_id_ocall_ret_long = 34,
    all_fcn_id_ocall_ret_size_t = 35,
    all_fcn_id_ocall_ret_unsigned = 36,
    all_fcn_id_ocall_ret_int8_t = 37,
    all_fcn_id_ocall_ret_int16_t = 38,
    all_fcn_id_ocall_ret_int32_t = 39,
    all_fcn_id_ocall_ret_int64_t = 40,
    all_fcn_id_ocall_ret_uint8_t = 41,
    all_fcn_id_ocall_ret_uint16_t = 42,
    all_fcn_id_ocall_ret_uint32_t = 43,
    all_fcn_id_ocall_ret_uint64_t = 44,
    all_fcn_id_ocall_ret_long_long = 45,
    all_fcn_id_ocall_ret_unsigned_char = 46,
    all_fcn_id_ocall_ret_unsigned_short = 47,
    all_fcn_id_ocall_ret_unsigned_int = 48,
    all_fcn_id_ocall_ret_unsigned_long = 49,
    all_fcn_id_ocall_ret_long_double = 50,
    all_fcn_id_ocall_ret_unsigned_long_long = 51,
    all_fcn_id_ocall_ret_void = 52,
    all_fcn_id_ocall_enum1 = 53,
    all_fcn_id_ocall_errno = 54,
    all_fcn_id_ocall_set_host_errno = 55,
    all_fcn_id_ocall_noop = 56,
    all_fcn_id_ocall_foreign_ptr_1 = 57,
    all_fcn_id_ocall_foreign_ptr_2 = 58,
    all_fcn_id_ocall_foreign_ptr_3 = 59,
    all_fcn_id_ocall_foreign_ptr_4 = 60,
    all_fcn_id_ocall_foreign_ptr_5 = 61,
    all_fcn_id_ocall_foreign_isptr_1 = 62,
    all_fcn_id_ocall_foreign_isptr_2 = 63,
    all_fcn_id_ocall_foreign_isptr_3 = 64,
    all_fcn_id_ocall_foreign_isptr_4 = 65,
    all_fcn_id_ocall_foreign_isptr_5 = 66,
    all_fcn_id_ocall_foreign_isary = 67,
    all_fcn_id_ocall_foreign_value = 68,
    all_fcn_id_ocall_pointer_char = 69,
    all_fcn_id_ocall_pointer_wchar_t = 70,
    all_fcn_id_ocall_pointer_short = 71,
    all_fcn_id_ocall_pointer_int = 72,
    all_fcn_id_ocall_pointer_float = 73,
    all_fcn_id_ocall_pointer_double = 74,
    all_fcn_id_ocall_pointer_long = 75,
    all_fcn_id_ocall_pointer_size_t = 76,
    all_fcn_id_ocall_pointer_unsigned = 77,
    all_fcn_id_ocall_pointer_int8_t = 78,
    all_fcn_id_ocall_pointer_int16_t = 79,
    all_fcn_id_ocall_pointer_int32_t = 80,
    all_fcn_id_ocall_pointer_int64_t = 81,
    all_fcn_id_ocall_pointer_uint8_t = 82,
    all_fcn_id_ocall_pointer_uint16_t = 83,
    all_fcn_id_ocall_pointer_uint32_t = 84,
    all_fcn_id_ocall_pointer_uint64_t = 85,
    all_fcn_id_ocall_pointer_long_long = 86,
    all_fcn_id_ocall_pointer_unsigned_char = 87,
    all_fcn_id_ocall_pointer_unsigned_short = 88,
    all_fcn_id_ocall_pointer_unsigned_int = 89,
    all_fcn_id_ocall_pointer_unsigned_long = 90,
    all_fcn_id_ocall_pointer_unsigned_long_long = 91,
    all_fcn_id_ocall_pointer_long_double = 92,
    all_fcn_id_ocall_count_attribute_all_types = 93,
    all_fcn_id_ocall_size_attribute_all_types = 94,
    all_fcn_id_ocall_pointer_assert_all_called = 95,
    all_fcn_id_ocall_string_fun1 = 96,
    all_fcn_id_ocall_string_fun2 = 97,
    all_fcn_id_ocall_string_fun3 = 98,
    all_fcn_id_ocall_string_fun5 = 99,
    all_fcn_id_ocall_string_fun6 = 100,
    all_fcn_id_ocall_string_fun7 = 101,
    all_fcn_id_ocall_wstring_fun1 = 102,
    all_fcn_id_ocall_wstring_fun2 = 103,
    all_fcn_id_ocall_wstring_fun3 = 104,
    all_fcn_id_ocall_wstring_fun5 = 105,
    all_fcn_id_ocall_wstring_fun6 = 106,
    all_fcn_id_ocall_wstring_fun7 = 107,
    all_fcn_id_ocall_string_no_null_terminator = 108,
    all_fcn_id_ocall_wstring_no_null_terminator = 109,
    all_fcn_id_ocall_struct1 = 110,
    all_fcn_id_ocall_sum = 111,
    all_fcn_id_switchless_ocall_sum = 112,
    all_fcn_id_host_foo1 = 113,
    all_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_ALL_ARGS_H
