/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_BAR_T_H
#define EDGER8R_BAR_T_H

#include <openenclave/enclave.h>

#include "bar_args.h"

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
void enc_bar(void);

/**** OCALL prototypes. ****/
oe_result_t host_bar(
    );

OE_EXTERNC_END

#endif // EDGER8R_BAR_T_H
