# Install script for directory: C:/Users/brmclare/openenclave/tests

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/opt/openenclave")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/lockless_queue/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/mem/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/safecrt/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/safemath/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/str/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/tools/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/aesm/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/debugger/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/host_verify/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/abortStatus/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/cppException/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/ecall/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/file/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/mbed/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/ocall-create/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/oeedger8r/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/stdcxx/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/thread/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/threadcxx/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/thread_local/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/thread_local_no_tdata/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/argv/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/attestation_cert_apis/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/backtrace/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/bigmalloc/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/crypto_crls_cert_chains/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/debug-mode/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/echo/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/enclaveparam/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/getenclave/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/ocall/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/print/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/props/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/qeidentity/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/report/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/SampleApp/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/SampleAppCRT/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/sealKey/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/stdc/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/syscall/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/VectorException/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/create-errors/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/crypto/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/hexdump/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/hostcalls/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/initializers/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/mixed_c_cpp/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/pingpong/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/pingpong-shared/cmake_install.cmake")
  include("C:/Users/brmclare/openenclave/tests/fuzztests/tests/fuzztests/cmake_install.cmake")

endif()

