# CMake generated Testfile for 
# Source directory: C:/Users/brmclare/openenclave/tests
# Build directory: C:/Users/brmclare/openenclave/tests/fuzztests/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("lockless_queue")
subdirs("mem")
subdirs("safecrt")
subdirs("safemath")
subdirs("str")
subdirs("tools")
subdirs("aesm")
subdirs("debugger")
subdirs("host_verify")
subdirs("abortStatus")
subdirs("cppException")
subdirs("ecall")
subdirs("file")
subdirs("mbed")
subdirs("ocall-create")
subdirs("oeedger8r")
subdirs("stdcxx")
subdirs("thread")
subdirs("threadcxx")
subdirs("thread_local")
subdirs("thread_local_no_tdata")
subdirs("argv")
subdirs("attestation_cert_apis")
subdirs("backtrace")
subdirs("bigmalloc")
subdirs("crypto_crls_cert_chains")
subdirs("debug-mode")
subdirs("echo")
subdirs("enclaveparam")
subdirs("getenclave")
subdirs("ocall")
subdirs("print")
subdirs("props")
subdirs("qeidentity")
subdirs("report")
subdirs("SampleApp")
subdirs("SampleAppCRT")
subdirs("sealKey")
subdirs("stdc")
subdirs("syscall")
subdirs("VectorException")
subdirs("create-errors")
subdirs("crypto")
subdirs("hexdump")
subdirs("hostcalls")
subdirs("initializers")
subdirs("mixed_c_cpp")
subdirs("pingpong")
subdirs("pingpong-shared")
subdirs("fuzztests")
