/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_TESTS_ARGS_H
#define EDGER8R_TESTS_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
#include "includes.h"

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _test_verify_qe_identity_info_args_t
{
    oe_result_t _result;
    oe_result_t _retval;
    char* info_json;
    size_t info_json_len;
    oe_parsed_qe_identity_info_t* parsed_info;
} test_verify_qe_identity_info_args_t;

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** Trusted function IDs ****/
enum
{
    tests_fcn_id_test_verify_qe_identity_info = 0,
    tests_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{

    tests_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_TESTS_ARGS_H
