/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_INITIALIZERS_U_H
#define EDGER8R_INITIALIZERS_U_H

#include <openenclave/host.h>

#include "initializers_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_initializers_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
#ifdef OE_CONTEXT_SWITCHLESS_EXPERIMENTAL_FEATURE
    const oe_enclave_config_t* configs,
    uint32_t config_count,
#else
    const void* config,
    uint32_t config_size,
#endif
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t get_globals(
    oe_enclave_t* enclave,
    int* global_int,
    float* global_float,
    int** global_ptr,
    dummy_struct* global_struct,
    dummy_union* global_union,
    int global_array[4],
    bool get_default);

oe_result_t set_globals(
    oe_enclave_t* enclave,
    int global_int,
    float global_float,
    int* global_ptr,
    dummy_struct global_struct,
    dummy_union global_union,
    int global_array[4],
    bool set_default);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_INITIALIZERS_U_H
