/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SEALKEY_U_H
#define EDGER8R_SEALKEY_U_H

#include <openenclave/host.h>

#include "sealKey_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_sealKey_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
#ifdef OE_CONTEXT_SWITCHLESS_EXPERIMENTAL_FEATURE
    const oe_enclave_config_t* configs,
    uint32_t config_count,
#else
    const void* config,
    uint32_t config_size,
#endif
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t test_seal_key(
    oe_enclave_t* enclave,
    int* _retval,
    int in);

oe_result_t enc_get_public_key_by_policy(
    oe_enclave_t* enclave,
    int* _retval,
    int policy,
    const char* data,
    uint8_t* keybuf,
    size_t keybuf_maxsize,
    size_t* keybuf_size,
    uint8_t* keyinfo,
    size_t keyinfo_maxsize,
    size_t* keyinfo_size);

oe_result_t enc_get_public_key(
    oe_enclave_t* enclave,
    int* _retval,
    const char* data,
    const uint8_t* keyinfo,
    size_t keyinfo_size,
    uint8_t* keybuf,
    size_t keybuf_maxsize,
    size_t* keybuf_size);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_SEALKEY_U_H
